### ISSUE TITLE
Error compiling to win32 or win64

### ISSUE THREAD

**Issue by zomorango** [Zeus64/alcinoe#102]
Using Delphi 10.3.3

Trying to compile the AlFFmxControls Sample.

[dcc64 Fatal Error] FMX.Types3D.pas(1023): F2051 Unit FMX.Materials was compiled with a different version of FMX.Types3D.TMaterial

**Comment by allancmello** [comment]
Same problem for me

**Comment by viniciusfbb** [comment]
Add to the Search path of your project
Project Options > Building > Delphi Compiler > Search path

**All configurations - All platforms**

alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\net
alcinoe\references\embarcadero\rio\10_3_3\patched\fmx
$(BDS)\source\rtl
$(BDS)\source\rtl\common
$(BDS)\source\rtl\net
$(BDS)\source\fmx

**All configurations - iOS Device 64-bit platform**

alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\ios
$(BDS)\source\rtl\ios

**All configurations - Android 64-bit platform**

alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\android


**Remarks**: The order is important!

**Comment by allancmello** [comment]
Hi @viniciusfbb this path **alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\net** 
don´t exists!

See the path in oficial github for alcinoe:

![image](https://user-images.githubusercontent.com/1229105/77215041-d0714180-6af0-11ea-8de4-3727b07de336.png)

![image](https://user-images.githubusercontent.com/1229105/77215107-2f36bb00-6af1-11ea-98b1-5f995ef0989e.png)

**Comment by viniciusfbb** [comment]
> Hi @viniciusfbb this path **alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\net**
> don´t exists!

Sorry, you're right! the "rtl\net" path don't exists in 10.3.3 patch, although it works the same way.

**Comment by zomorango** [comment]
Thanks Vinicius, that solved the problem :)
