### ISSUE TITLE
Error using ALTabControl

### ISSUE THREAD

**Issue by zomorango** [Zeus64/alcinoe#103]
Using Delphi Rio 10.3.3
I've created a new Delphi multi-device project,

Drag a ALTabControl into the form,
press Run and Error
`
[dcc32 Error] ALFmxLayouts.pas(142): E2137 Method 'ChildrenMouseDown' not found in base class
[dcc32 Error] ALFmxLayouts.pas(143): E2137 Method 'ChildrenMouseMove' not found in base class
[dcc32 Error] ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseUp' not found in base class
[dcc32 Error] ALFmxLayouts.pas(145): E2137 Method 'ChildrenMouseLeave' not found in base class
[dcc32 Fatal Error] ALFmxTabControl.pas(18): F2063 Could not compile used unit 'ALFmxLayouts.pas'
`

**Comment by viniciusfbb** [comment]
Your project is not finding the modified delphi sources. Please follow the guidelines in the other topic
https://github.com/Zeus64/alcinoe/issues/102#issuecomment-601801956

**Comment by zomorango** [comment]
Once again thank you very mush it's working now
