### ISSUE TITLE
ALImage -  Resourse Image.png not found

### ISSUE THREAD

**Issue by zomorango** [Zeus64/alcinoe#104]
I'm trying to use ALImage component, in design time type the name of the image  in the Resourcename an filename properties and I can see the imagen. but when I run the app I get the error Resource- image.png not found.
Using Rio 10.3.3 and win32 compile

**Comment by Zeus64** [comment]
hello ALImage work by taking the image from a resource Or from from a file (but not both). it work a little differently in design time as at this time the resource are not yet available so it's look for a file in extractFilePath(getActiveProject.fileName) + 'resources\' + fResourceName

try to set only resourcename (and include the file in the resource => resources and images) or try to set only the filename
