### ISSUE TITLE
About WebRTC

### ISSUE THREAD

**Issue by lewis50093** [Zeus64/alcinoe#105]
Excuse me (I' m from Taiwan ,so please don't mind my poor english..)
First,thanks your component, It is very good!
When I try to open Demo ALLiveVideoChat and run to ios Device
and has error "[DCC Error] E2597 ld: warning: directory not found for option '-LC:\Dev\Alcinoe\demos\ALLiveVideoChat\client\_source\ios\frameworks\WebRTC.framework'
  ld: file not found: WebRTC"
I know Its need to install framework from "\lib\ios\webrtc"
But I dont understand how to install 
Can anyone help me ? Thank you  and have good time

**Comment by Zeus64** [comment]
Hi lewis. everything is explained in {Alcinoe_rootdir}\lib\ios\webrtc\readme.txt

The framework must be signed with the same team identifier in the main executable code signature.
The team identifier is the 10-character alphanumeric string, such as YH9SZ5LKR4, associated with your developer account, 
and recorded in your Apple-issued signing certificate.

You must do this manually still embarcadero implement it
https://quality.embarcadero.com/browse/RSP-22899

codesign -s <Identity> /YourPathto/WebRTC.framework/WebRTC

After you need to deploy yourself the WebRTC.framework in the .\Frameworks\WebRTC.framework
file to deploy: 
  Info.plist
  LICENSE.md
  WebRTC
  _CodeSignature\CodeResources
  
  
Stripping Unwanted Architectures From WebRTC
http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

lipo -info /YourPathto/WebRTC.framework/WebRTC
lipo -remove i386 /YourPathto/WebRTC.framework/WebRTC -o /YourPathto/WebRTC.framework/WebRTC 
lipo -remove x86_64 /YourPathto/WebRTC.framework/WebRTC -o /YourPathto/WebRTC.framework/WebRTC
lipo -info /YourPathto/WebRTC.framework/WebRTC
