### ISSUE TITLE
Try to compile with the new Rio version but.. error

### ISSUE THREAD

**Issue by azrael11** [Zeus64/alcinoe#106]
says cant find the methods below in the ALFmxLayouts.pas

[dcc64 Error] ALFmxLayouts.pas(142): E2137 Method 'ChildrenMouseDown' not found in base class
[dcc64 Error] ALFmxLayouts.pas(143): E2137 Method 'ChildrenMouseMove' not found in base class
[dcc64 Error] ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseUp' not found in base class
[dcc64 Error] ALFmxLayouts.pas(145): E2137 Method 'ChildrenMouseLeave' not found in base class
[dcc64 Fatal Error] ALFmxTabControl.pas(18): F2063 Could not compile used unit 'ALFmxLayouts.pas'
Failed
Elapsed time: 00:00:01.1

**Comment by aam4gian** [comment]
you can follow this [video ](https://www.youtube.com/watch?v=JI14Qxwsc_U)to install alcinoe 

but in this video There is no guide for copying original files from '**C:\Program Files (x86)\Embarcadero\Studio\20.0\source**' the alcinoe library folder alcinoe-master-lates\references\embarcadero\rio\10_3_3\originals

and add to search path delphi compiler your project, you can see this in demo configuration project

![image](https://user-images.githubusercontent.com/62690731/77995446-fd75ed80-7355-11ea-8a25-7b16be9fc538.png)

**Comment by Zeus64** [comment]
@aam4gian Thanks for this great video !!

**Comment by Zeus64** [comment]
I just updated the readme.md (section Install alcinoe in https://github.com/Zeus64/alcinoe/) with the instruction to install alcinoe
