### ISSUE TITLE
Json - Array parse 

### ISSUE THREAD

**Issue by orhanOzyurt** [Zeus64/alcinoe#108]
First I want to say **Thanks** for that great library.
when I want to parse an array like below, I got  "JSON parse error" .
`[{"value":"0.02045601","speed":"5.30400000"},{"value":"0.00594700","speed":"40.70000000"}]`
I tried to reach firs array object as **AjsonDoc.childnodes[0]**....... but it doesn't work.
how can I fix it, thanks

**code:**

`  AJsonDoc := TalJsonDocument.create;
  AjsonDoc.loadFromJsonString('[{"value":"0.02045601","speed":"5.30400000"},{"value":"0.00594700","speed":"40.70000000"}]');
  Form1.memo1.Lines.add(AjsonDoc.childnodes[0].childnodes['value'].text);
  AJsonDoc.free;`

tried to add '0.02045601' to memo1

**Comment by Zeus64** [comment]
[{"value":"0.02045601","speed":"5.30400000"},{"value":"0.00594700","speed":"40.70000000"}] is not a valid json doc, a valid jsondoc start with { and end with }. you must do somethink like AjsonDoc.loadFromJsonString('{"rootnode":[{"value":"0.02045601","speed":"5.30400000"},{"value":"0.00594700","speed":"40.70000000"}]}');

**Comment by orhanOzyurt** [comment]
thanks alot :)
