### ISSUE TITLE
ImageMagick. NewMagickWandFromImage ?

### ISSUE THREAD

**Issue by Izdatyi** [Zeus64/alcinoe#111]
Hello!
I need to load image from source (stream or bytes, not from file) to Wand
Is there a function for this? I found this:  
[NewMagickWandFromImage](https://www.imagemagick.org/api/magick-wand.php#NewMagickWandFromImage)
`WandExport MagickWand* NewMagickWandFromImage ( const Image *  image )`
But I have problems with parameter 'Image *  image'
How can I implement this to Delphi?
Or maybe there is another way to load image directly to Wand blob in memory?
Thanks.

PS Sorry for my English )

**Comment by Zeus64** [comment]
you can use MagickReadImageBlob for this

        if ALImageMagickLib.MagickReadImageBlob(aWand,
                                                aPicStream.Memory,
                                                aPicStream.Size) <> MagickTrue then RaiseLastMagickWandError(aWand);
