### ISSUE TITLE
plz update webrtc libs

### ISSUE THREAD

**Issue by RDP1974** [Zeus64/alcinoe#113]
please can you update the webrtc with latest webrtc / google-webrtc / 1.0.30039?
your libs are more than 16 months old, and webrtc is evolving very fast 
or can you tell me how to update then I'll upload in the repository
thank you

**Comment by Zeus64** [comment]
It's a full time job to keep updated all the time with last libs (not only webrtc, firebase, google, facebook, etc.)  :( But is even more hard with webRtc where they redraw everything quite often. But if you want to make a try and share your result I will be very thanks :)

**Comment by Zeus64** [comment]
how to upgrade the lib is explaining here:
https://github.com/Zeus64/alcinoe/tree/master/lib/ios/webrtc
and
https://github.com/Zeus64/alcinoe/tree/master/lib/jar/org.webrtc
