### ISSUE TITLE
how to handle a virtual keyboard

### ISSUE THREAD

**Issue by aam4gian** [Zeus64/alcinoe#115]
hello, 
I was stuck how to handle a virtual keyboard, so that makes the ALEdit or ALMemo component directly above the bounded virtual keyboard. I tried to follow the method in the demo example, but the one above the virtual keyboard is always the lowest component. I am trying to add a layout in ALVertScrollBox1 with the intention to play the top margin of the layout so that it can push the ALEdit component that is in focus downwards. following the [github demo](https://github.com/aam4gian/virtualkeyboard) link that I made. if you want to add one method to the ALFmxControls demo project or fix the code in my sample project.

**Comment by Zeus64** [comment]
this is how i did i my app (add a Layout in the mainForm with align = ALclient and play with the padding bottom of the mainform when keyboard is show/hidden)

```
procedure TMainForm.FormVirtualKeyboardHidden(Sender: TObject; KeyboardVisible: Boolean; const Bounds: TRect);
begin
  fKeyboardOpen := false;
  Padding.Bottom := 0;
end;

procedure TMainForm.FormVirtualKeyboardShown(Sender: TObject; KeyboardVisible: Boolean; const Bounds: TRect);
begin
  fKeyboardOpen := True;
  padding.Bottom := Bounds.height;
end;

```

**Comment by aam4gian** [comment]
I have tried playing the padding values, but haven't gotten the formula that is right for every change of focus control
