### ISSUE TITLE
10.3.3: Unit FMXTee.Canvas problem

### ISSUE THREAD

**Issue by pasiek22** [Zeus64/alcinoe#116]
Hi !

I use TChart components in my project.
I get the following error during compilation:

[dcc32 Fatal Error] main.pas(12): F2051 Unit FMXTee.Canvas was compiled with a different version of FMX.Edit.TEdit

Can anyone help?

**Comment by Zeus64** [comment]
@pasiek22 please follow the instruction in https://github.com/Zeus64/alcinoe, especially "Install Alcinoe"
`
If after this you have error like (for exemple) [dcc32 Fatal Error] FMX.Types3D.pas(1023): F2051 Unit FMX.Materials was compiled with a different version of FMX.Types3D.TMaterial. then you need also to include in you search path non patched units (here FMX.Materials.pas for exemple) that are located in your C:\Program Files (x86)\Embarcadero\Studio\20.0\source\ directory You can copy thoses files in (for exemple)`
