### ISSUE TITLE
TALXMLDocument demoted

### ISSUE THREAD

**Issue by acastiello** [Zeus64/alcinoe#119]
Why was TALXMLDocument demoted to TObject instead of TComponent, and why so many properties were removed? I have tons of code that no longer compiles, not even opens properly in the Delphi 10 IDE. Is there a replacemente for it?

**Comment by Zeus64** [comment]
hello acastiello, you mean compared to TXMLDocument ? TALXMLDocument is not descending from TComponent because for such class their is quite no good reason to put it in the component palette to be later able to put it in the form designer. I keep the same idea of TXMLDocument but I didn't keep everything, for example TXMLDocument is from interface (so you don't need to free it) but TALXMLDocument is from Tobject. At the time i wrote TALXMLDocument (more than 10 years ago) they was troubles with interface and i prefer to control the memory

**Comment by acastiello** [comment]
Sorry to hear that. I used it a lot (and I mean a lot) as a component. It was my favorite XML document handler. TXMLDocument still is a component in Delphi 10. I don´t see the good reason no to put it in the palette. Anyway, I´m working in making TAlXMLDocument Delphi 10 compatible. I have lot of code that uses it as a component and clearly, it will be faster to migrate it to Delphi 10 than to rewrite my code to use another (even TXmlDocument). Regards

**Comment by Zeus64** [comment]
yes I understand, it's a different habit to put everything on the form, some like you like this way and some others don't. but to be curious why you want to replace your TXMLDocument? what wrong with them ?

**Comment by acastiello** [comment]
In fact my scenario is much like yours. I like to separate visual from meaty code. I have several datamodules that contain **TAlXmlDocument** components (not TXMLDocument). Such code was written in Delphi 2007 and time has come to say goodbye to this old friend. But now, those datamodules flag several errors just by openning them in Delphi 10, since _TAlXmlDocument_ is no longer a component but a object. Again, and apologies for insisting, but I see no reason to demote it and remove existing properties

**Comment by Zeus64** [comment]
But I don't understand you mean TALXmlDocument was a component in the past? you already use TALXmlDocument (not TXMLDocument) in your Delphi 2007 project ?

**Comment by acastiello** [comment]
Unless we shifted form parallel universes, the answer to both questions is yes, ha ha. About eight years ago I was looking for a good XML component, and the whole Alcinoe suite showed up in sourceforge. I downloaded and installed it in Delphi 2007. I made the same with the current version on Delphi 10.3.3 but since _TALXmlDocument_ is no longer a component, the source flags errors complaining TALXmlDocument is not found
![TAlXMLDocument](https://user-images.githubusercontent.com/60796982/80226647-4007ae80-8612-11ea-851e-b0115d080640.jpg)

**Comment by Zeus64** [comment]
@acastiello I understand now :) and your project is still aleave 8 years after that very great! In fact to correct your problem you will need just to change one line of code in ALXmlDoc.pas, just replacing TALXMLDocument = class(TObject) by TALXMLDocument = class(TComponent) and register also TALXmlDocument in the tool palette. Maybe it's the best way to go, just patch on your side the TALXmlDocument ?

nowadays, 8 years later, the use of XML decrease hugely as everyone move to JSON so even us we don't use too much XML anymore so i don't think this unit will change often so patching it seam a good way to go.

**Comment by acastiello** [comment]
Unfortunately is not that easy. Properties and events are gone from the current _TAlXmlDocument_ . Since my current old version (3.55) works fine, I´ll patch it to compile and run with Delphi 10 (the unicode and stuff about it) and will post it here when it´s done. Regards

**Comment by Zeus64** [comment]
@acastiello yes it's sound a good solution :) I close this ticket in the meantime
