### ISSUE TITLE
ALVideoPlayer under Windows

### ISSUE THREAD

**Issue by vkrapotkin** [Zeus64/alcinoe#121]
I haven't find the way the ALVideoPlayer acting under Windows

Paint method just calls inherited TALRectangle.Paint. So it simply draws black rectangle and no more.
Does it mean that ALVideoPlayer not work in Windows ?

**Comment by Zeus64** [comment]
@vkrapotkin unfortunately ALVideoPlayer is not working (not even implemented) under windows right now it's work only under android/ios :(
