### ISSUE TITLE
failed compile ALLiveVideoChatClient already present: android.support.annotation.AnimRes

### ISSUE THREAD

**Issue by sernocturno** [Zeus64/alcinoe#124]
Hi, i have a problem when i try to compile the video chat client, i already make the changes on codegear.common.targets, change the old dx.bat and change the sdk path and the alcinoe jar lib path on the new dx.bat, but when i try to compile the project, the compiler throw the next error:

> [Exec Error] EXEC(1): Program type already present: android.support.annotation.AnimRes

That's when i enable the android-support-v4.dex.jar, when i disable it the project compile the project, but when i run it, the app crash and the adb monitor throw this error:

> 05-10 22:10:15.112: D/AndroidRuntime(15026): Shutting down VM
> 05-10 22:10:15.120: E/AndroidRuntime(15026): FATAL EXCEPTION: main
> 05-10 22:10:15.120: E/AndroidRuntime(15026): Process: com.embarcadero.ALLiveVideoChatClient, PID: 15026
> 05-10 22:10:15.120: E/AndroidRuntime(15026): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/OnApplyWindowInsetsListener;
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at java.lang.Class.newInstance(Native Method)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1237)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3040)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.os.Looper.loop(Looper.java:193)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at java.lang.reflect.Method.invoke(Native Method)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.OnApplyWindowInsetsListener" on path: DexPathList[[zip file "/data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/lib/arm, /data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 05-10 22:10:15.120: E/AndroidRuntime(15026): 	... 15 more

hope somebody can help

**Comment by Zeus64** [comment]
Failed resolution of: Landroid/support/v4/view/OnApplyWindowInsetsListener
did you include successfully all the support v4 jars located in alcinoe\lib\ ?

**Comment by sernocturno** [comment]
Hi, thanks for your time.
I'm not sure if you mean those libraries
![imagen](https://user-images.githubusercontent.com/19215335/81562620-8d528280-936b-11ea-9fc0-83c6cca25694.png)

or if you mean the library pat on the dx.bat, by the way i set the librariesroothpath like this
`set librariesRootPath=D:\Jakemate\Componentes_DXE10\alcinoe-master\lib\jar`
 and the _d8cmd is
`SET _d8Cmd=%_dxCmd:dx.bat"=d8.bat"!_extraParams! --lib C:\Users\Marcelo.Marcelo-PC\AppData\Local\Android\Sdk\platforms\android-29\android.jar%`

p\d: The compiler have a strange behavior when start compiling, because is like if it try to run a file name classes.dex

![imagen](https://user-images.githubusercontent.com/19215335/81561985-7c554180-936a-11ea-9d53-7858da77f757.png)

after i close the dialog the compiler still running, but is strange

**Comment by Zeus64** [comment]
this is for exemple the sample in my project:

![image](https://user-images.githubusercontent.com/4325047/81563537-a9b7e480-9396-11ea-98c4-5d59ff944943.png)

you need much more jars, please look carefully the jars included in the demo,

**Comment by sernocturno** [comment]
still having the error `Landroid/support/v4/view/OnApplyWindowInsetsListener` and i literally include all the jar's on the project

**Comment by Zeus64** [comment]
@sernocturno you miss one, in the screenshot I didn't show you all the jars. OnApplyWindowInsetsListener  is located in support-compat.jar.
