### ISSUE TITLE
Failed resolution of: Landroid/support/v4/view/OnApplyWindowInsetsListener

### ISSUE THREAD

**Issue by sernocturno** [Zeus64/alcinoe#125]
Hi. i have a problem with the app, the adb monitor show this error and crash

`5-10 22:10:15.120: E/AndroidRuntime(15026): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.OnApplyWindowInsetsListener" on path: DexPathList[[zip file "/data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/lib/arm, /data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]`

im using all the jar lib on the project but still happening

**Comment by Zeus64** [comment]
you forget to add the jar in the <alcinoe_lib>/lib/jars/ in your projects. I don't know with jar you miss, look the demo in <alcinoe_lib>/demos/ALLiveVideoChat/

**Comment by sernocturno** [comment]
im runing the demo ALLiveVideoChat and it not compile, the target is ok and the dx is ok
i dont miss any jar, because i use the 54 jar that you have in the folder and still not working 
![imagen](https://user-images.githubusercontent.com/19215335/81604206-eb03c080-93a5-11ea-8640-ce2f832461bc.png)

this is the problem

`5-10 22:10:15.120: E/AndroidRuntime(15026): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.OnApplyWindowInsetsListener" on path: DexPathList[[zip file "/data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/lib/arm, /data/app/com.embarcadero.ALLiveVideoChatClient-MCSgs87f9knyPE_dR4pbXQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]`

**Comment by Zeus64** [comment]
I don't understand where it's go wrong :( look like the support-compat.jar wasn't deployed! maybe something goes wrong with the dx.bat. look the log that go out from the dx.bat (if you use the one provider in <alcinoeroot>/tools/
