### ISSUE TITLE
64 bit

### ISSUE THREAD

**Issue by antarey** [Zeus64/alcinoe#127]
Target platform 64 bit
Error compile
[dcc64 Fatal Error] Alcinoe_rio.dpk(36): E2202 Required package 'DesignIDE' not found

**Comment by Zeus64** [comment]
@antarey i do not understand, why you compile to 64 bit the Alcinoe_rio.dpk ? delphi IDE is only 32 bit, so you can not compile for 64 bit, you must compile for 32 bit
