### ISSUE TITLE
Access violation in Delphi designer

### ISSUE THREAD

**Issue by pwill** [Zeus64/alcinoe#13]
@loki: When i install your components in Tokyo, put a TAlScrollbox on it and switch away from design mode and back or load a project, i get a access violation in fmx250.bpl, and when i compile my test project anyway i get an error telling me that TAlScrollBox isn't found. (maybe that is caused by delphi not being able to show the designer)
I attached the error log. (PS. thank you so much for your hard work, you're great! Too bad embarcadero doesn't hire you and other bright minds to evolve delphi)

[0BA7F470]

{fmx250.bpl } FMX.Controls.TControl.GetMargins (Line 3703, "FMX.Controls.pas" + 0) + $0
[0BA82410]
{fmx250.bpl }
FMX.Controls.TControl.SetBounds (Line 4954, "FMX.Controls.pas" + 2) + $5F
[50067898]

{rtl250.bpl } System.@IntfClear (Line 37239, "System.pas" + 10) + $0
[5005F9E8]
{rtl250.bpl }
System.TObject.GetInterface (Line 17320, "System.pas" + 8) + $A
[1FAAA848]

{Alcinoe_tokyo.bpl} Alfmxinertialmovement.TALAniCalculations.IsSmall + $C
[1FAAC02A]
{Alcinoe_tokyo.bpl}
Alfmxinertialmovement.TALAniCalculations.UpdateTimer + $DA
[1FAAB78E]

{Alcinoe_tokyo.bpl} Alfmxinertialmovement.TALAniCalculations.SetTargets + $11A
[5005F9E8]
{rtl250.bpl } System.TObject.GetInterface (Line 17320, "System.pas" + 8) + $A
[5005FA31]
{rtl250.bpl } System.TObject.GetInterface (Line 17327, "System.pas" + 15) + $10
[0BA82410]
{fmx250.bpl } FMX.Controls.TControl.SetBounds (Line 4954, "FMX.Controls.pas" + 2) + $5F
[0BA7F4FE]
{fmx250.bpl } FMX.Controls.TControl.GetLocalRect (Line 3743, "FMX.Controls.pas" + 1) + $28
[1FB20BD3]
{Alcinoe_tokyo.bpl}
Alfmxlayouts.TALCustomScrollBox.CalcContentBounds + $C7
[1FB20FE9]

{Alcinoe_tokyo.bpl} Alfmxlayouts.TALCustomScrollBox.GetTabList + $3E5
[1FB2100D]
{Alcinoe_tokyo.bpl}
Alfmxlayouts.TALCustomScrollBox.GetTabList + $409
[1FB21026]

{Alcinoe_tokyo.bpl} Alfmxlayouts.TALCustomScrollBox.GetTabList + $422
[5006FCCE]
{rtl250.bpl } System.Types.TRectF.EqualsTo (Line 2543, "System.Types.pas" + 1) + $19
[1FB213C0]
{Alcinoe_tokyo.bpl}
Alfmxlayouts.TALCustomScrollBox.DoRealign + $D8
[0BA7FA44]

{fmx250.bpl } FMX.Controls.TControl.Realign (Line 3896, "FMX.Controls.pas" + 16) + $4
[0BA8275F]
{fmx250.bpl }
FMX.Controls.TControl.InternalSizeChanged (Line 5034, "FMX.Controls.pas" + 16) + $2
[0BA80A1E]

{fmx250.bpl } FMX.Controls.TControl.HandleSizeChanged (Line 4242, "FMX.Controls.pas" + 6) + $2
[0BA80AE6]
{fmx250.bpl }
FMX.Controls.TControl.SizeChanged (Line 4269, "FMX.Controls.pas" + 9) + $4
[0BA7C1A5]

{fmx250.bpl }
FMX.Controls.TControl.RecalcSize (Line 2716, "FMX.Controls.pas" + 3) + $8
[0F155FBD]

{fmxdesigner250.bpl} FmxFormContainer.TFormContainerForm.RefreshControl (Line 740, "FmxFormContainer.pas" + 5) + $4
[0F156A5F]
{fmxdesigner250.bpl}
FmxFormContainer.TFormContainerForm.NeedStyleLookup (Line 752, "FmxFormContainer.pas" + 5) + $5
[0F15775F]

{fmxdesigner250.bpl} FmxFormContainer.TFormContainerForm.SetMasterStyle (Line 1195, "FmxFormContainer.pas" + 7) + $2
[0F15CE73]
{fmxdesigner250.bpl}
FmxFormContainer.TFormBoundary.SetMasterStyle (Line 3060, "FmxFormContainer.pas" + 2) + $7
[212598F8]

{designide250.bpl} EmbeddedFormDesigner.TEditorFormDesigner.DoSelectStyle (Line 135, "EmbeddedFormDesigner.pas" + 10) + $9
[21256A66]
{designide250.bpl}
ViewSelector.TViewSelectorFrame.cbStyleSelectorChange (Line 329, "ViewSelector.pas" + 2) + $2D
[2125791E]

{designide250.bpl} ViewSelector.TViewSelectorFrame.SelectStyle (Line 726, "ViewSelector.pas" + 16) + $C
[5006103C]
{rtl250.bpl } System.@TryFinallyExit (Line 22405, "System.pas" + 8) + $0
[212578CF]
{designide250.bpl}
ViewSelector.TViewSelectorFrame.SelectStyle (Line 720, "ViewSelector.pas" + 10) + $0
[2125A0A9]

{designide250.bpl} EmbeddedFormDesigner.TEditorFormDesigner.SelectPreviewStyle (Line 340, "EmbeddedFormDesigner.pas" + 2) + $8
[0F155EE0]
{fmxdesigner250.bpl} FmxFormContainer.TFormContainerForm.SelectMasterStyle (Line 730, "FmxFormContainer.pas" + 22) + $9
[0F156AD1]
{fmxdesigner250.bpl} FmxFormContainer.TFormContainerForm.Activate (Line 764, "FmxFormContainer.pas" + 1) + $2
[0F157E2E]
{fmxdesigner250.bpl} FmxFormContainer.TFmxEditorFormDesignerWrapper.DisplayDesigner (Line 1503, "FmxFormContainer.pas" + 13) + $7
[2125B2FD]
{designide250.bpl}
EmbeddedDesignerForm.TFormEditorView.Display (Line 202, "EmbeddedDesignerForm.pas" + 18) + $8
[207EAF49]

{coreide250.bpl} EditorForm.TEditWindow.ShowView (Line 4395, "EditorForm.pas" + 50) + $B
[207E50BC]
{coreide250.bpl}
EditorForm.TEditWindow.SwitchViews (Line 2157, "EditorForm.pas" + 8) + $5
[207E4C0E]

{coreide250.bpl} EditorForm.TEditWindow.ViewBarChange (Line 2005, "EditorForm.pas" + 3) + $C
[035072D9]
{vcl250.bpl } Vcl.Tabs.TTabSet.CanChange (Line 1933, "Vcl.Tabs.pas" + 3) + $D
[0350732A]
{vcl250.bpl } Vcl.Tabs.TTabSet.SetTabIndex (Line 1944, "Vcl.Tabs.pas" + 5) + $4
[035075B4]
{vcl250.bpl } Vcl.Tabs.TTabSet.MouseDown (Line 2056, "Vcl.Tabs.pas" + 6) + $6
[033352B8]
{vcl250.bpl } Vcl.Controls.TControl.DoMouseDown (Line 7477, "Vcl.Controls.pas" + 7) + $2B
[03335307]
{vcl250.bpl } Vcl.Controls.TControl.WMLButtonDown (Line 7488, "Vcl.Controls.pas" + 7) + $E
[03334C5E]
{vcl250.bpl } Vcl.Controls.TControl.WndProc (Line 7338, "Vcl.Controls.pas" + 91) + $6
[204E8EBE]
{coreide250.bpl}
IDETimerServices.AFKCBTProc (Line 239, "IDETimerServices.pas" + 6) + $F
[03339051]

{vcl250.bpl } Vcl.Controls.TWinControl.IsControlMouseMsg (Line 9972, "Vcl.Controls.pas" + 9) + $2A
[03339843]
{vcl250.bpl }
Vcl.Controls.TWinControl.WndProc (Line 10209, "Vcl.Controls.pas" + 166) + $6
[03338E10]

{vcl250.bpl } Vcl.Controls.TWinControl.MainWndProc (Line 9908, "Vcl.Controls.pas" + 3) + $6
[5016EBCC]
{rtl250.bpl } System.Classes.StdWndProc (Line 17408, "System.Classes.pas" + 11) + $2
[03482F90]
{vcl250.bpl }
Vcl.Forms.TApplication.StopHintTimer (Line 11369, "Vcl.Forms.pas" + 3) + $3
[03481E1F]

{vcl250.bpl } Vcl.Forms.TApplication.ProcessMessage (Line 10641, "Vcl.Forms.pas" + 23) + $1
[03481E62]
{vcl250.bpl }
Vcl.Forms.TApplication.HandleMessage (Line 10671, "Vcl.Forms.pas" + 1) + $4
[03482195]

{vcl250.bpl }
Vcl.Forms.TApplication.Run (Line 10809, "Vcl.Forms.pas" + 26) + $3
[005088F2]

{bds.exe }
bds.bds (Line 212, "" + 7) + $7

**Comment by Zeus64** [comment]
hmm, with version of tokyo do you have ?
Do you also see this bug with the demo project located in Alcinoe\demos\ALFmxControls\ ?

**Comment by pwill** [comment]
If i run the compile_tokyo.bat and tell it to build demos it won't compile demos and say "ALCommon.pas" not found.
But it builds the BPL files and im also able to install "Alcinoe_tokyo.dpk"...
Then i make a fresh empty form, place a AlScrollbox on it and close the form or switch to source and back.

**Comment by Zeus64** [comment]
> >> If i run the compile_tokyo.bat and tell it to build demos it won't compile demos and say "ALCommon.pas" 


For this you must add in the delphi source path the path to "...\Alcinoe\source". also Some demos will not compile because they are made with devExpress library (but other must compile good)

after when it's compiled you can include in delphi the unit Alcinoe\lib\bpl\alcinoe\Win32\tokyo\Alcinoe_tokyo.bpl to add the visual control in the delphi tool palette 

> Then i make a fresh empty form, place a AlScrollbox on it and close the form or switch to source and back.

I can't reproduce :( what delphi version are you using ?

**Comment by pwill** [comment]
Installation of the bpl runs fine and also it finds the unit and i already added the folder to the library path...
The source just can't be found when i run the bat and tell it to compile the demos...
If i install the DPK it adds it to delphi and when i add a component to my form, switch away from the form designer and back to it, the access violation happens...

Im using the most recent 10.2.3 Pro

**Comment by Zeus64** [comment]
I just correct this bug, it's was a typo mistake in the code ... just update with the last version and say me if you still have the bug ....

**Comment by pwill** [comment]
Yes, now it works. Thanks. You're great!
