### ISSUE TITLE
hint about desktop grabbing

### ISSUE THREAD

**Issue by ghost** [Zeus64/alcinoe#135]
hello,

I want use this API https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api
to grab the desktop video and send through webRTC client.

Perhaps do you have samples or hints about the direct3d surface to map into FMX texture and use in ALwebRtc?

Or do you know a better API to grab desktop and send to D3D surface?

thank you

**Comment by Zeus64** [comment]
the main problem is that the implementation I made for WebRTC is only for android and iOS :( I didn't implement anything on windows, you will need to start from scratch :(

**Comment by RDP1974** [comment]
thanks for your info, I'll go to use the library directly

**Comment by Zeus64** [comment]
I close this issue as it's related to webrtc and windows and we support only WebRTC through mobile
