### ISSUE TITLE
Making a HTTP Post with JSON Data

### ISSUE THREAD

**Issue by EcoFa** [Zeus64/alcinoe#138]
Hi,

we are currently trying to implement a HTTP post with the Alcinoe "TalWinHttpClient" component.
In some cases we have to transfer data in JSON format in the post method.

Unfortunately we get the error message 415 - Unsupported Media Type.

In the header configuration the values Accept and ContentType are already transferred with application/json.

We get this error message also in the demo, if we send the following JSON to the server:

```
{
        "Source":{
            "CountryCode":"DE",
            "ZIPCode":"38106"
        },
        "Destination":{
            "CountryCode":"DE",
            "ZIPCode":"65779"
        }
}
```

Is there any setting to transfer the data in JSON format?

**Comment by Zeus64** [comment]
normally setting ContentType to application/json is enough. maybe the problem is on the server-side ? what the URL of the server ? some old server accept only application/javascript. conrect is
Content-Type: application/json

**Comment by EcoFa** [comment]
Thank you very much for the quick feedback. The error was due to me, I had given an empty string as body parameter for this Post Request, because no body should be sent for this Post Request. This led to the error.
