### ISSUE TITLE
Project ALFmxControls.apk raised exception class EJNIFatal with message 'Invoke error:method not found'.

### ISSUE THREAD

**Issue by TomYU6** [Zeus64/alcinoe#14]
app raise error message when i run app at android phone and android version is 4.4.4

**Comment by Zeus64** [comment]
Kitkat is old version of Android, normally it's must work, can you can me the full error message ? I mean when you receive Invoke error:method not found their is also the name of the method somewhere in the message (i guess)

**Comment by TomYU6** [comment]
When running the app in debug mode, I can't see which method was not found. Just see this error message:Invoke error:method not found

**Comment by Zeus64** [comment]
can you plug the android device monitor when you run the app and see in the logcat the full error message ?

**Comment by aloisjunior** [comment]
Hello, in my tests the error occurred in
fSurfaceTexture.setOnFrameAvailableListener (FOnFrameAvailableListener, fHandler);
I also had this problem and "solved" it so
try fSurfaceTexture.setOnFrameAvailableListener (FOnFrameAvailableListener, fHandler); // original
    except
fSurfaceTexture.setOnFrameAvailableListener (FOnFrameAvailableListener); // api android <21
    end;

But by calling without locking the handle there are crashes in the video ...
Any light on it would help a lot.

**Comment by TomYU6** [comment]
06-21 07:48:01.227: E/libEGL(22476): call to OpenGL ES API with no current context (logged once per thread)
06-21 07:48:01.227: E/libEGL(22476): call to OpenGL ES API with no current context (logged once per thread)
06-21 07:48:01.227: E/libEGL(22476): validate_display:254 error 3008 (EGL_BAD_DISPLAY)
06-21 07:48:01.227: E/libEGL(22476): call to OpenGL ES API with no current context (logged once per thread)
06-21 07:48:01.417: E/dalvikvm(22476): Could not find class 'com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23', referenced from method com.google.android.exoplayer2.video.MediaCodecVideoRenderer.clearRenderedFirstFrame
06-21 07:48:01.417: E/dalvikvm(22476): Could not find class 'com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23', referenced from method com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec
06-21 07:48:01.437: E/dalvikvm(22476): Could not find class 'android.media.AudioAttributes$Builder', referenced from method com.google.android.exoplayer2.audio.DefaultAudioSink.createAudioTrackV21
06-21 07:48:01.437: E/dalvikvm(22476): Could not find class 'android.media.AudioFormat$Builder', referenced from method com.google.android.exoplayer2.audio.DefaultAudioSink.createAudioTrackV21
06-21 07:48:01.447: E/dalvikvm(22476): Could not find class 'android.media.AudioAttributes$Builder', referenced from method com.google.android.exoplayer2.audio.AudioAttributes.getAudioAttributesV21

**Comment by Zeus64** [comment]
Ok, i see where the error is, i will commit soon an update to work with android kitkat
