### ISSUE TITLE
Error compiling for ios  with sensor Location

### ISSUE THREAD

**Issue by zomorango** [Zeus64/alcinoe#146]
Hi, 
First of all let me say that I just love this Lib, Stephane Bravo, wonderful work,
I've done an app for Android using Location service using the component from the embarcadero fmx palette tools, It works fine, and using ALcinoe for speed up my effects and lists smooth scrolling, everything is great.
Now I'm trying to run it om my iPhone 7 plus and get this error
[DCC Error] System.iOS.Sensors.pas(125): E2291 Missing implementation of interface method CLLocationManagerDelegate.locationManagerDidVisit,

Note that is I build a small app without using Alcinoe and  using the same code for the Location service it works and compile fine,

I'm using Delphi Rio 10.3.3

Does any one have an Idear on how to solve this ??

**Comment by Zeus64** [comment]
Thanks for the compliments :) .. yes it's because you need to include in your path the the patch units located in Alcinoe\references\embarcadero\rio\10_3_3\patched :)

**Comment by zomorango** [comment]
Hi Stéphane,
In my Search path I have this

alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\net
alcinoe\references\embarcadero\rio\10_3_3\patched\fmx
$(BDS)\source\rtl
$(BDS)\source\rtl\common
$(BDS)\source\rtl\net
$(BDS)\source\fmx
alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\ios
$(BDS)\source\rtl\ios
$(BDS)\source\rtl\osx

Still getting the same error

**Comment by zomorango** [comment]
Note that I'm getting the error  in this unit
[DCC Fatal Error] System.Sensors.pas(768): F2063 Could not compile used unit 'System.iOS.Sensors.pas'

**Comment by Zeus64** [comment]
just this error? nothing more ?

**Comment by zomorango** [comment]
and  also the cause ,
[DCC Error] System.iOS.Sensors.pas(125): E2291 Missing implementation of interface method CLLocationManagerDelegate.locationManagerDidVisit,

so it's the same error as before

**Comment by zomorango** [comment]
I also try in the ALFmxControls demo, I just put a TlocationSensor component on the main form and when I try to compile it I got the same error.

**Comment by Zeus64** [comment]
so your patch is wrong! you must put full path not only alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\net (ex: c:\alcinoe\references\embarcadero\rio\10_3_3\patched\rtl\net)

**Comment by zomorango** [comment]
Hi ,
Yes  Stéphane I know :) , I have the full path ,  not only "alcinoe" ,  the actual full path is big h:\Tools\CrossPlatform\delphitools\fmx\alcinoe... I just put alcinoe in my message to be more readable, sorry for that...

**Comment by zomorango** [comment]
I managed to make it work :)
