### ISSUE TITLE
TalWebRTC documentation available?

### ISSUE THREAD

**Issue by behcettolga** [Zeus64/alcinoe#155]
Hi Zeus64,

is there some sort of boiler plate / documentation for your webRTC wrapper?
I browsed this issue forum and understand that the wrapper is only for the mobile platforms.
This was a little suprising since when you open the  AllLiveVideoChat project group, the target platform appears as Win32. And I could compile without issues...

I am trying to build a solution where people can connect to video meetings from Desktop Client and browsers / mobile.
On which platforms the demo client & server pieces should be running?

Thanks for your efforts!

**Comment by Zeus64** [comment]
Hi behcettolga, right now it's only on mobile. yes it's compile on desktop but it's not implemented under desktop :( If you feel the courage to implement it let's go :)
