### ISSUE TITLE
10.4 / 10.4.1 compatibility? 

### ISSUE THREAD

**Issue by jdredd87** [Zeus64/alcinoe#159]
Says 10.3.3 compatibility.

When will 10.4 or better ,10.4.1 compatibility be added? Since this introduced changes to remove ARC.

**Comment by firemen01** [comment]
`I will do my best to do it as soon as possible, maybe with the 10.4.2`

**Comment by Zeus64** [comment]
Sorry it's was a long way :( The source code is now compatible with 10.4.2
