### ISSUE TITLE
Build issue IOS

### ISSUE THREAD

**Issue by Spelt** [Zeus64/alcinoe#16]
Hi

Thanks for the controls. I love them.

I just did a pull to get the latest.  Everything compiles except for IOS.  I get:

ALGraphics.pas(3337): E2003 Undeclared identifier: 'setValueforKey'
ALGraphics.pas(3337): E2003 Undeclared identifier: 'kCIInputImageKey'
ALGraphics.pas(3341): E2003 Undeclared identifier: 'kCIInputRadiusKey'

I use the latest Delphi with all the patches.  

Is there something I need to include for the IOS side of things?

Thanks!
Edward

**Comment by Zeus64** [comment]
thanks Spelt

yes theses value was missing from iOSapi.Foundation.pas & iOSapi.CoreImage.pas so I add them manually (https://quality.embarcadero.com/browse/RSP-19878 & https://quality.embarcadero.com/browse/RSP-19877)

You can find patched unit (delphi tokyo 10.2.2) in demos\ALFmxControls\_source\embarcadero\tokyo\

**Comment by Spelt** [comment]
Hi Loki,

Don’t see the change yet. Can you push your changes to the repo?

**Comment by Zeus64** [comment]
change are in this directory: Alcinoe\demos\ALFmxControls\_source\embarcadero\tokyo\

**Comment by Spelt** [comment]
Ok I get it now.

Thanks!
