### ISSUE TITLE
firebase auth support

### ISSUE THREAD

**Issue by RakeshShrestha** [Zeus64/alcinoe#161]
The library does firebase messaging .. it will be great if it supports firebase auth email, phone etc ..

**Comment by Zeus64** [comment]
yes, but right now I try to reduce at maximum my dependency to google (and we see why with huaway). firebase messaging is the only way to send notification in android phone with play store so no other choice, but for auth their is plenty of other solution available. personally I prefer to use the api of facebook, VKontakte, etc.. to connect to their services.
