### ISSUE TITLE
When will Alcinoe 10.4 be released?

### ISSUE THREAD

**Issue by LeeHyunChul777** [Zeus64/alcinoe#162]
We are so happy that Alcinoe has been released.
Perhaps Alcinoe is an essential part of Delphi.

When will Alcinoe 10.4 be released?

I'm using 10.3.3, only TALRectangle, TALText, and TALVertScrollBox.

Can I use TALRectangle, TALText, and TALVertScrollBox components when upgrading to 10.4?

**Comment by mateusvicente100** [comment]
Hi @LeeHyunChul777 I have an fork of Alcinoe and I use the same components of you on Delphi 10.4.1. I don't use any other, so I can't say if will work. Perhaps, TALRectangle, TALText, and TALVertScrollBox I use on Android and iOS fine.

https://github.com/mateusvicente100/alcinoe

In this fork I add a new component to TALLabelEdit. Take I look.

**Comment by Zeus64** [comment]
Sorry it's was a long way, it's now available for 10.4.2
