### ISSUE TITLE
Linebreak(s) ignored in TAlText if immediately before html tag

### ISSUE THREAD

**Issue by rj1102** [Zeus64/alcinoe#17]
Using build 773, using TAlText with TextIsHtml and WordWrap set to True, if I put a linebreak prior to a html tag, the line break is ignored:

  AlText1.Text := 'Line 1' + System.sLineBreak + 'Line 2'; // works fine
  AlText1.Text := 'Line 1' + System.sLineBreak + '&lt;b>Line 2&lt;/b>'; // linebreak is ignored

Any workaround is appreciated.

**Comment by Zeus64** [comment]
yes I know about this little bug I will update soon the algorithm. right now I add space after the line break but it's clearly not a perfect workaround :(

**Comment by Zeus64** [comment]
corrected in last version of alcinoe

**Comment by rj1102** [comment]
Confirmed, but just as info for other users:
It is still (as of r865) a workaround: you now should replace #13#10'<b>' with '<b>'#13#10 (so linebreak after in stead of before tag. It is not logical to do so, but it works, and it is a better workaround than inserting an unwanted space.

**Comment by Zeus64** [comment]
but now with the last commited version #13#10<b> must work like it is intended to work ?

**Comment by rj1102** [comment]
yes, i’ve rechecked it, and it works now (r865).
Strange, when i retested with r865 yesterday, it seemed not to work (and it was confirmed by the comments in ALFmxCommon.pas - line 320 - that it still contains a bug regarding #13#10). Maybe i did some mix up with an older version of ALFmxCommon.pas since I made some code changes to get rectangle linear gradient working, can not explain it otherwise.

Anyway, thanks for fixing!

**Comment by rj1102** [comment]
I've just found my test case that does not work:

`AlText1.Text := 'Line 1' + System.sLineBreak + System.sLineBreak + '<b>Line 2</b>';`

So **two** linebreaks before a tag.

But it can be simply workaround with: 
`AlText1.Text := 'Line 1' + System.sLineBreak + '<b>' + System.sLineBreak + 'Line 2</b>';`
