### ISSUE TITLE
About ALVideoPlayer

### ISSUE THREAD

**Issue by cyc001** [Zeus64/alcinoe#171]
Hi. Thank you for the update for last version of Sydney.

About ALVideoPlayer:
1.If only TALVideoPlayerSurface  in the project : On Android, video can be displayed.On windows system, video cannot be played.

2.If the two components [TFDConnection  and TALVideoPlayerSurface ] are used in the project, compilation error occurs  {"[DCC Fatal Error] F2051 Unit FireDAC.FMXUI.Wait was compiled with a different version of FMX.Forms.Application"}. then I dont use the search Path : "alcinoe-master\embarcadero\sydney\10_4_2\fmx", the project can be compiled ok,but audio can be heared,No image.

Regards.

**Comment by Zeus64** [comment]
Hi,

1/ TALVideoPlayerSurface do not work on Windows right now, it's only for mobile (ios/android) :( I m working to integrating a patch a user gave me to make it working under macos

2/ so it's mean you need also to add the path to <embarcadero>\source\data\FireDAC\ in your project search path (or copy the file in your project directory)

**Comment by cyc001** [comment]
Thank you for your reply ！
