### ISSUE TITLE
build demo ‘ALFmxControls’

### ISSUE THREAD

**Issue by jonahzheng** [Zeus64/alcinoe#174]
dephi 10.4.2
[DCC Error] ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseDown' not found in base class
[DCC Error] ALFmxLayouts.pas(145): E2137 Method 'ChildrenMouseMove' not found in base class
[DCC Error] ALFmxLayouts.pas(146): E2137 Method 'ChildrenMouseUp' not found in base class
[DCC Error] ALFmxLayouts.pas(147): E2137 Method 'ChildrenMouseLeave' not found in base class

**Comment by Zeus64** [comment]
this is because you didn't include in your search path the <alcinoe_root>\embarcadero\sydney\10_4_2\...
