### ISSUE TITLE
about update.bat

### ISSUE THREAD

**Issue by jonahzheng** [Zeus64/alcinoe#175]
delphi 10.4.2
run \alcinoe\embarcadero\sydney\10_4_2\update.bat

==========================================

**    Change;
  end;
end;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Graphics.pas:2949
error: embarcadero/sydney/10_4_2/fmx/FMX.Graphics.pas: patch does not apply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Materials.Canvas.pas...
error: while searching for:
    {$ENDREGION}

    {$REGION 'TContextShaderArch.GLSL'}
    TContextShaderSource.Create(TContextShaderArch.GLSL, [
      $76, $61, $72, $79, $69, $6E, $67, $20, $76, $65, $63, $34, $20, $43, $4F,
 $4C, $4F, $52, $30, $3B, $0D, $0A, $76, $61, $72, $79, $69, $6E, $67, $20, $76,
 $65, $63, $34, $20, $54, $45, $58, $30, $3B,
      $0D, $0A, $76, $65, $63, $34, $20, $5F, $72, $65, $74, $5F, $30, $3B, $0D,
 $0A, $66, $6C, $6F, $61, $74, $20, $5F, $54, $4D, $50, $31, $3B, $0D, $0A, $66,
 $6C, $6F, $61, $74, $20, $5F, $54, $4D, $50,
      $30, $3B, $0D, $0A, $76, $65, $63, $32, $20, $5F, $63, $30, $30, $30, $38,
 $3B, $0D, $0A, $75, $6E, $69, $66, $6F, $72, $6D, $20, $73, $61, $6D, $70, $6C,
 $65, $72, $32, $44, $20, $5F, $74, $65, $78,
      $74, $75, $72, $65, $30, $3B, $0D, $0A, $76, $6F, $69, $64, $20, $6D, $61,
 $69, $6E, $28, $29, $0D, $0A, $7B, $0D, $0A, $20, $20, $20, $20, $76, $65, $63,
 $34, $20, $5F, $74, $65, $78, $43, $6F, $6C,
      $6F, $72, $3B, $0D, $0A, $20, $20, $20, $20, $5F, $54, $4D, $50, $30, $20,
 $3D, $20, $66, $72, $61, $63, $74, $28, $54, $45, $58, $30, $2E, $78, $29, $3B,
 $0D, $0A, $20, $20, $20, $20, $5F, $54, $4D,
      $50, $31, $20, $3D, $20, $66, $72, $61, $63, $74, $28, $54, $45, $58, $30,
 $2E, $79, $29, $3B, $0D, $0A, $20, $20, $20, $20, $5F, $63, $30, $30, $30, $38,
 $20, $3D, $20, $76, $65, $63, $32, $28, $5F,
      $54, $4D, $50, $30, $2C, $20, $5F, $54, $4D, $50, $31, $29, $3B, $0D, $0A,
 $20, $20, $20, $20, $5F, $74, $65, $78, $43, $6F, $6C, $6F, $72, $20, $3D, $20,
 $74, $65, $78, $74, $75, $72, $65, $32, $44,
      $28, $5F, $74, $65, $78, $74, $75, $72, $65, $30, $2C, $20, $5F, $63, $30,
 $30, $30, $38, $29, $3B, $0D, $0A, $20, $20, $20, $20, $5F, $72, $65, $74, $5F,
 $30, $20, $3D, $20, $5F, $74, $65, $78, $43,
      $6F, $6C, $6F, $72, $2A, $43, $4F, $4C, $4F, $52, $30, $3B, $0D, $0A, $20,
 $20, $20, $20, $67, $6C, $5F, $46, $72, $61, $67, $43, $6F, $6C, $6F, $72, $20,
 $3D, $20, $5F, $72, $65, $74, $5F, $30, $3B,
      $0D, $0A, $20, $20, $20, $20, $72, $65, $74, $75, $72, $6E, $3B, $0D, $0A,
 $7D, $20, $0D, $0A], [
      TContextShaderVariable.Create('texture0', TContextShaderVariableKind.Textu
re, 0, 0)]
    )
    {$ENDREGION}

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Materials.Canvas.pas:440
error: embarcadero/sydney/10_4_2/fmx/FMX.Materials.Canvas.pas: patch does not ap
ply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Platform.iOS.pas...
error: while searching for:
{*******************************************************}
{                                                       }
{              Delphi FireMonkey Platform               }
{                                                       }

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Platform.iOS.pas:1
error: embarcadero/sydney/10_4_2/fmx/FMX.Platform.iOS.pas: patch does not apply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Platform.UI.Android.pas...
error: while searching for:
  Androidapi.JNI.Embarcadero, Androidapi.JNI.GraphicsContentViewText, Androidapi
.JNI.Widget, Androidapi.JNI.JavaTypes,
  Androidapi.Input, Androidapi.NativeActivity, Androidapi.Helpers, FMX.Forms, FM
X.Types, FMX.Types3D, FMX.KeyMapping,
  FMX.Helpers.Android, FMX.Controls, FMX.Text, FMX.Graphics, FMX.Gestures, FMX.V
irtualKeyboard, FMX.Consts, FMX.Utils,
  FMX.Platform, FMX.MultiTouch.Android, FMX.ZOrder.Android, FMX.Platform.Text.An
droid;

type

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Platform.UI.Android.pas:1
8
error: embarcadero/sydney/10_4_2/fmx/FMX.Platform.UI.Android.pas: patch does not
 apply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.StrokeBuilder.pas...
error: while searching for:
  FUndeterminedMode := True;
  InitArrayPointers;

  StepSize := FThickness;
  if StepSize < 2 then
    StepSize := 2;

  CurIndex := 0;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.StrokeBuilder.pas:1074
error: embarcadero/sydney/10_4_2/fmx/FMX.StrokeBuilder.pas: patch does not apply

Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Types3D.pas...
error: while searching for:
  begin
    FContextLostId := -1;
    FContextResetId := -1;
  end;
end;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Types3D.pas:3089
error: embarcadero/sydney/10_4_2/fmx/FMX.Types3D.pas: patch does not apply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.VirtualKeyboard.Android.pas...
error: while searching for:
  VKRect.TopLeft := ConvertPixelToPoint(TPointF.Create(newFrame.Left, newFrame.T
op)).Round;
  VKRect.BottomRight := ConvertPixelToPoint(TPointF.Create(newFrame.Right, newFr
ame.Bottom)).Round;

  if (FNeedNotifyAboutFrameChanges or ((MainActivity.getVirtualKeyboard.isVirtua
lKeyboardShown) and (VKRect.Height > 0)))
     and (FPreviousVKRect <> VKRect) then
    try
      FKeyboardService.SendNotificationAboutKeyboardEvent(VKRect);
      FPreviousVKRect := VKRect;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.VirtualKeyboard.Android.p
as:213
error: embarcadero/sydney/10_4_2/fmx/FMX.VirtualKeyboard.Android.pas: patch does
 not apply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Android.pas...
error: while searching for:
    FChildrenContainer: JViewGroup;
    FURL: string;
    [Weak] FWebControl: TCustomWebBrowser;
    function GetZOrderManager: TAndroidZOrderManager;
  protected
    function QueryInterface(const IID: TGUID; out Obj): HResult; stdcall;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Android.pas:70

error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Android.pas: patch does not
apply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Cocoa.pas...
error: while searching for:

  TCommonWebBrowserService = class(TInterfacedObject, ICustomBrowser)
  private
    FWebView: INativeWebView;
    FURL: string;
    FWebControl: TCustomWebBrowser;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Cocoa.pas:45
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Cocoa.pas: patch does not ap
ply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.pas...
error: while searching for:
    function GetParent: TFmxObject;
    function GetVisible : Boolean;
    procedure UpdateContentFromControl;
    procedure Navigate;
    procedure Reload;
    procedure Stop;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.pas:40
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.pas: patch does not apply
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Win.pas...
error: while searching for:
    procedure SetWebBrowserControl(const AValue: TCustomWebBrowser);
    function GetVisible: Boolean;
    procedure UpdateContentFromControl;
    procedure Navigate;
    procedure Reload;
    procedure Stop;

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Win.pas:70
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Win.pas: patch does not appl
y
Checking patch embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.App.pas...
error: while searching for:
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.Os,
  Androidapi.JNI.Util,
  Androidapi.JNI.Widget;

type
// ===== Forward declarations =====

error: patch failed: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.App.pa
s:16
error: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.App.pas: patch does
not apply
Checking patch embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.Location.pas
...
error: while searching for:
    procedure unregisterGnssMeasurementsCallback(callback: JGnssMeasurementsEven
t_Callback); cdecl;
    procedure unregisterGnssNavigationMessageCallback(callback: JGnssNavigationM
essage_Callback); cdecl;
    procedure unregisterGnssStatusCallback(callback: JGnssStatus_Callback); cdec
l;
  end;
  TJLocationManager = class(TJavaGenericImport<JLocationManagerClass, JLocationM
anager>) end;

error: patch failed: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.Locati
on.pas:660
error: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.Location.pas: patch
does not apply
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.AVFoundation.pas...
error: while searching for:
    function timedMetadata: NSArray; cdecl;
    function tracks: NSArray; cdecl;
    function videoComposition: AVVideoComposition; cdecl;
  end;
  TAVPlayerItem = class(TOCGenericImport<AVPlayerItemClass, AVPlayerItem>)  end;

error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.AVFoundation.pas:7
30
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.AVFoundation.pas: patch does not
 apply
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreImage.pas...
error: while searching for:
  end;
  TCIFaceFeature = class(TOCGenericImport<CIFaceFeatureClass, CIFaceFeature>)  e
nd;

implementation

end.

error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreImage.pas:218
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreImage.pas: patch does not ap
ply
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreLocation.pas...
error: while searching for:
  kCLAuthorizationStatusNotDetermined = 0;
  kCLAuthorizationStatusRestricted = 1;
  kCLAuthorizationStatusAuthorizedAlways  = kCLAuthorizationStatusAuthorized ;
  kCLAuthorizationStatusAuthorizedWhenInUse = 4;
  kCLErrorDenied = 1;
  kCLErrorGeocodeCanceled = 10;
  kCLErrorGeocodeFoundNoResult = 8;

error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreLocation.pas:3
3
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreLocation.pas: patch does not
 apply
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Foundation.pas...
error: while searching for:
      downloadTask: NSURLSessionDownloadTask; didResumeAtOffset: Int64; expected
TotalBytes: Int64); cdecl;
  end;

// Convenience method for creating an NSString from a Delphi Unicode string
function NSSTR(const Str: string): NSString; inline; deprecated 'use StrToNSStr
instead';

error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Foundation.pas:556
6
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Foundation.pas: patch does not a
pply
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Security.pas...
error: while searching for:
function kSecAttrKeyClassSymmetric: NSString;
function kSecAttrKeyTypeRSA: NSString;
function kSecAttrKeyTypeEC: NSString;

implementation

error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Security.pas:620
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Security.pas: patch does not app
ly
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.UIKit.pas...
error: while searching for:
    function currentUserNotificationSettings: UIUserNotificationSettings; cdecl;

    function delegate: UIApplicationDelegate; cdecl;
    function enabledRemoteNotificationTypes: Pointer; cdecl;
    procedure endBackgroundTask(identifier: Pointer); cdecl;
    procedure endIgnoringInteractionEvents; cdecl;
    procedure endReceivingRemoteControlEvents; cdecl;
    procedure ignoreSnapshotOnNextApplicationLaunch; cdecl;

error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.UIKit.pas:3828
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.UIKit.pas: patch does not apply
Checking patch embarcadero/sydney/10_4_2/rtl/win/Winapi.Isapi2.pas...
error: while searching for:
    dwReserved: DWORD): Pointer; stdcall;

  TFilterServerSupportFunctionProc = function (var pfc{: THTTP_FILTER_CONTEXT};
    sfReq: DWORD; pData: Pointer; ul1, ul2: DWORD): BOOL; stdcall;

  PHTTP_FILTER_CONTEXT = ^THTTP_FILTER_CONTEXT;
  THTTP_FILTER_CONTEXT = record

error: patch failed: embarcadero/sydney/10_4_2/rtl/win/Winapi.Isapi2.pas:397
error: embarcadero/sydney/10_4_2/rtl/win/Winapi.Isapi2.pas: patch does not apply

==========================================================================

![image](https://user-images.githubusercontent.com/5125282/117157603-4c137800-adf1-11eb-99aa-7ea014c3a7d9.png)
![image](https://user-images.githubusercontent.com/5125282/117157632-53d31c80-adf1-11eb-998e-637d2ef855e6.png)
![image](https://user-images.githubusercontent.com/5125282/117157665-5c2b5780-adf1-11eb-9c92-18bec1e660f7.png)
![image](https://user-images.githubusercontent.com/5125282/117157686-62213880-adf1-11eb-8e23-f9cbb6845019.png)
![image](https://user-images.githubusercontent.com/5125282/117157416-2ab28c00-adf1-11eb-82c5-11c03da9ae29.png)

**Comment by Zeus64** [comment]
are you sure you have sydney 10.4.2 and the  corresponding source file located in c:\Program Files (x86)\Embarcadero\Studio\21.0\source ?

**Comment by jonahzheng** [comment]
yes
c:\Program Files (x86)\Embarcadero\Studio\21.0\source
![image](https://user-images.githubusercontent.com/5125282/117220823-99680780-ae3a-11eb-942b-1ba51ee7a557.png)

**Comment by Zeus64** [comment]
But is it the 10.4.2 (ie: update 2 of sydney) ? maybe you have the 10.4.1 ?

**Comment by enri690** [comment]
Hi. I am not in front of the computer right now,  but from what I remember the update.bat has a path problem. You may need to execute the script from the parent folder.

**Comment by jonahzheng** [comment]
only 10.4.2
![image](https://user-images.githubusercontent.com/5125282/117299536-3bbfd380-aeab-11eb-894b-0e91461d7907.png)
![image](https://user-images.githubusercontent.com/5125282/117299696-690c8180-aeab-11eb-8698-73d8cd9b8407.png)

============================================
e:\Rad\Lib\alcinoe\embarcadero\sydney\10_4_2>git apply --check sydney_10_4_2.pat
ch
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas:12

error: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas: patch does not
apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.pas:72
error: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Context.GLES.pas:188
error: embarcadero/sydney/10_4_2/fmx/FMX.Context.GLES.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Controls.pas:113
error: embarcadero/sydney/10_4_2/fmx/FMX.Controls.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Dialogs.iOS.pas:246
error: embarcadero/sydney/10_4_2/fmx/FMX.Dialogs.iOS.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Edit.pas:11
error: embarcadero/sydney/10_4_2/fmx/FMX.Edit.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Filter.pas:11
error: embarcadero/sydney/10_4_2/fmx/FMX.Filter.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Forms.pas:9
error: embarcadero/sydney/10_4_2/fmx/FMX.Forms.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Graphics.pas:2949
error: embarcadero/sydney/10_4_2/fmx/FMX.Graphics.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Materials.Canvas.pas:440
error: embarcadero/sydney/10_4_2/fmx/FMX.Materials.Canvas.pas: patch does not ap
ply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Platform.iOS.pas:1
error: embarcadero/sydney/10_4_2/fmx/FMX.Platform.iOS.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Platform.UI.Android.pas:1
8
error: embarcadero/sydney/10_4_2/fmx/FMX.Platform.UI.Android.pas: patch does not
 apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.StrokeBuilder.pas:1074
error: embarcadero/sydney/10_4_2/fmx/FMX.StrokeBuilder.pas: patch does not apply

error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.Types3D.pas:3089
error: embarcadero/sydney/10_4_2/fmx/FMX.Types3D.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.VirtualKeyboard.Android.p
as:213
error: embarcadero/sydney/10_4_2/fmx/FMX.VirtualKeyboard.Android.pas: patch does
 not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Android.pas:70

error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Android.pas: patch does not
apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Cocoa.pas:45
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Cocoa.pas: patch does not ap
ply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.pas:40
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Win.pas:70
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Win.pas: patch does not appl
y
error: patch failed: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.App.pa
s:16
error: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.App.pas: patch does
not apply
error: patch failed: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.Locati
on.pas:660
error: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.Location.pas: patch
does not apply
error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.AVFoundation.pas:7
30
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.AVFoundation.pas: patch does not
 apply
error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreImage.pas:218
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreImage.pas: patch does not ap
ply
error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreLocation.pas:3
3
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreLocation.pas: patch does not
 apply
error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Foundation.pas:556
6
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Foundation.pas: patch does not a
pply
error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Security.pas:620
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Security.pas: patch does not app
ly
error: patch failed: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.UIKit.pas:3828
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.UIKit.pas: patch does not apply
error: patch failed: embarcadero/sydney/10_4_2/rtl/win/Winapi.Isapi2.pas:397
error: embarcadero/sydney/10_4_2/rtl/win/Winapi.Isapi2.pas: patch does not apply

=============================================


> But is it the 10.4.2 (ie: update 2 of sydney) ? maybe you have the 10.4.1 ?

**Comment by jonahzheng** [comment]
modify update.bat
===================
echo Patch the source code
git apply --ignore-space-change --ignore-whitespace sydney_10_4_2.patch -v
IF ERRORLEVEL 1 goto ERROR
echo.
==============

run ok.

**Comment by Zeus64** [comment]
Great thanks !!
