### ISSUE TITLE
ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseDown' not found in base class

### ISSUE THREAD

**Issue by gonzzzales** [Zeus64/alcinoe#182]
Please help me to compile my program. I want to use TTabControl, but on compile i see 5 errors

[dcc32 Error] ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseDown' not found in base class
[dcc32 Error] ALFmxLayouts.pas(145): E2137 Method 'ChildrenMouseMove' not found in base class
[dcc32 Error] ALFmxLayouts.pas(146): E2137 Method 'ChildrenMouseUp' not found in base class
[dcc32 Error] ALFmxLayouts.pas(147): E2137 Method 'ChildrenMouseLeave' not found in base class
[dcc32 Fatal Error] ALFmxTabControl.pas(19): F2063 Could not compile used unit 'ALFmxLayouts.pas'

What i need to do? 
I have delphi 10.4.1

**Comment by Zeus64** [comment]
Oh I didn't see, you have the 10.4.1 :( the patch work only on the 10.4.2 :( you will need to update source code manually or to update to delphi 10.4.2
