### ISSUE TITLE
Issue to play mp4 file with new 10.4.2 Alcinoe components

### ISSUE THREAD

**Issue by Yarpda** [Zeus64/alcinoe#193]
Hi. 
I have an issue  with my Delphi 10.3 project when I run it on 10.4.2 with new Alcinoe components. On 10.3 my mp4 file was played good, video and sound. On 10.4.2 same file plays only sound and on shows when [picture](http://f0422859.xsph.ru/1other/1.jpg) on playSurface.

New alcinoe components was installed succefuly. Update.bat was runned, pathed files was added to source path. jar filed in project was replaced by new 10.4.2. version.

How to fix this issue?

**Comment by Zeus64** [comment]
hello yarpa, can you try to play the mp4 on the demo app (alfmxControls). on with OS? android or iOS?

**Comment by Yarpda** [comment]
> hello yarpa, can you try to play the mp4 on the demo app (alfmxControls). on with OS? android or iOS?

Ок. I will try. Android OS. Will reply later.

**Comment by Yarpda** [comment]
I tryed to compile that project on another computer with 10.4.2 components, and its works fine. I think this is some local problem. Thanks, issue is solved.
