### ISSUE TITLE
Android TAlRectangle: setting radius at run time does not work

### ISSUE THREAD

**Issue by rj1102** [Zeus64/alcinoe#20]
Using build r862
It appeared to me that setting TAlRectangle.XRadius and YRadius at run time does not work under Android (Windows works fine; iOS not able to test):

uses ALFmxObjects;
{...}
procedure TForm1.Button1Click(Sender: TObject);
begin
  AlRectangle1.XRadius := 10;
  AlRectangle1.YRadius := 10;
end; // nothing happens under Android

**Comment by Zeus64** [comment]
Yes it's because the rectangle image is cached in memory and you need to reset the cache after changing some properties of the object. To do this simply do :

AlRectangle1.XRadius := 10;
AlRectangle1.YRadius := 10;
AlRectangle1.clearBufBitmap;
