### ISSUE TITLE
ALVideoPlayer  - problem with playback 

### ISSUE THREAD

**Issue by JerryMacNow** [Zeus64/alcinoe#215]
Hi, maybe someone can give me some suggestions. Have been struggling with this for the second day. Trying to run Video on Android.

I added exoplayer-hls.jar and exoplayer-core.jar libraries.
ALFmxControls demo works very well. But in my example I get these errors:

![image](https://user-images.githubusercontent.com/89270707/131912003-933cc055-9506-4fb5-922a-cb321da9da6d.png)

I'd appreciate any help

**Comment by Zeus64** [comment]
the error say that unable to connect? look stupid but is the Internet working well ?

**Comment by JerryMacNow** [comment]
I just found a solution. I do not know why, but your link does not work. When I upload the mp4 to my server, everything is OK. I lost a lot of time on this :/

**Comment by JerryMacNow** [comment]
BTW. thank you for the great library !!!. I hope you will develop it because I want to make a cool app :)
