### ISSUE TITLE
[DCC Fatal Error] dwsXPlatform.pas(47): F2613 Unit 'Windows' not found.

### ISSUE THREAD

**Issue by JerryMacNow** [Zeus64/alcinoe#216]
Your json library is great. I have no problem under Windows. However, I can't compile for Android. There is no 
Windows.pas library. Why this library for Android ? Where to find it ?

![image](https://user-images.githubusercontent.com/89270707/132699164-db302ed1-09e7-413c-b7de-cf7aa9b62f38.png)

**Comment by Zeus64** [comment]
I think their is a mistake, dwsXPlatform is not from alcinoe :)

**Comment by JerryMacNow** [comment]
OK, thank you
