### ISSUE TITLE
ALPhpRunner use problem

### ISSUE THREAD

**Issue by TomYU6** [Zeus64/alcinoe#22]
Hello,
ALPhpRunner how to call the following this type of URL:
http://localhost/index.php/hello/world

Best regards

**Comment by Zeus64** [comment]
No ALPhpRunner can be use only to run local php code (like myscript.php) and get the output. The url http://localhost/index.php/hello/world is a webpage and you can only download the result via http (using TalHttpClient or indy for exemple). It's the webserver who will run the php script

please don't forget to star (like) this project of ghitub if you like it

**Comment by TomYU6** [comment]
Is a local call, but need to pass QUERY_STRING parameters, I don't really understand how do you pass this parameter?
Such as:
QUERY_STRING = goto = newpost&t = 1

My index.php file URL is called "index.php/hello = world", also may be "index.php/hello/world", such parameters how to pass?

**Comment by Zeus64** [comment]
Did you already star (like) this project of ghitub (like I kindly asked you) ? Why i will spend time to help people (And I even not count the time to build the code that I gave for free) if those people can not even spend 1 ms to click on a "star" button ??

**Comment by Zeus64** [comment]
try to see the demo ALPhpRunner to find out how to execute PHP script ...
