### ISSUE TITLE
[ALMongoDBClient ] How to get _id ?

### ISSUE THREAD

**Issue by megatkurniawan** [Zeus64/alcinoe#225]
Hello, 
how do I retrieve the _id data using the ALMongoDBClient library. 
i tried it but get unknown character result like this.
![image](https://user-images.githubusercontent.com/25611625/142582876-b4589629-4ac8-4cf2-8d12-b513c9764b0b.png)

thank you

**Comment by Zeus64** [comment]
_Id is not a String but an ObjectID, that mean it's contain binary characters (not printable). If you want to print it you must use something like ALBinToHex(MyJson.ObjectID) for exemple
