### ISSUE TITLE
Mute/stop video running in background

### ISSUE THREAD

**Issue by JerryMacNow** [Zeus64/alcinoe#226]
Hi everybody !

I am making an application which uses the Video component. 
I have this problem. The application works fine,  but when I run / switch other application, I hear the Video sound all the time in background.  The same problem is when I blank the screen. How can I detect that the screen has been blanked, or there has been a switch to another application ?

**Comment by Zeus64** [comment]
to detect when the app go in background you can do :

  var LAppEventSvc: IFMXApplicationEventService;
  if TPlatformServices.Current.SupportsPlatformService(IFMXApplicationEventService, IInterface(LAppEventSvc)) then
    LAppEventSvc.SetApplicationEventHandler(MyApplicationEventHandler);
