### ISSUE TITLE
Error when compiling for iOS - ALGraphics

### ISSUE THREAD

**Issue by vgartner** [Zeus64/alcinoe#26]
I've attached an image showing the error, that occurs when compiling unit ALGraphics.

![alcinoe-error](https://user-images.githubusercontent.com/3457129/44377384-dea14b00-a4d2-11e8-8aaa-4ac1bb194a6f.PNG)

**Comment by Zeus64** [comment]
It's because you didn't include the modified version of original delphi source code in your search path. You can find them (for delphi tokyo 10.2.3) in demos\ALFmxControls\_source\embarcadero\tokyo\
