### ISSUE TITLE
ALVideoPlayerSurface1.VideoPlayer.Start is cant  use 

### ISSUE THREAD

**Issue by github889900** [Zeus64/alcinoe#27]
i use 
ALVideoPlayerSurface1.VideoPlayer.Stop

then is use
ALVideoPlayerSurface1.VideoPlayer.Start

but  the  Start  events  is not play then  video

**Comment by Zeus64** [comment]
you must use ALVideoPlayerSurface1.VideoPlayer.pause instead of ALVideoPlayerSurface1.VideoPlayer.Stop
