### ISSUE TITLE
how use  ALVideoPlayerSurface1.VideoPlayer.setCurrentPosition

### ISSUE THREAD

**Issue by github889900** [Zeus64/alcinoe#28]
i only use  ALVideoPlayerSurface1.VideoPlayer.getCurrentPosition

but  how to use  ALVideoPlayerSurface1.VideoPlayer.setCurrentPosition

thanks

**Comment by Zeus64** [comment]
setCurrentPosition is not yet implemented :( but you can try to implement it, it's must be very easy and similar to getCurrentPosition
