### ISSUE TITLE
TALTabControl.CMGesture doesn't send up and down gesture message to parent control

### ISSUE THREAD

**Issue by PonyPC** [Zeus64/alcinoe#3]
TALTabControl.CMGesture doesn't send up and down gesture message to parent control

**Comment by Zeus64** [comment]
thanks for the report, I will look at it this week

**Comment by PonyPC** [comment]
@Zeus64 Excuse, do you know how to send up and down mouse event to parent control such as Scrollbox,  like a real drag scroll in scrollbox.

**Comment by PonyPC** [comment]
Emmm... it's emb bug.
Put a GestureManager on Form instead Frame can fix this.
