### ISSUE TITLE
About NetHTTPClient

### ISSUE THREAD

**Issue by Yorke81** [Zeus64/alcinoe#30]
Hi,The same error message will appear when using the ALVideoPlayer and NetHTTPClient components in the project.
[DCC Fatal Error] Unit1.pas(7): F2051 Unit System.Net.HttpClient.Mac was compiled with a different version of Macapi.Helpers.NSStrToStr

**Comment by Zeus64** [comment]
You need to include in the source path or the project the original Macapi.Helpers.pas from the delphi source code

**Comment by Yorke81** [comment]
![1536287678](https://user-images.githubusercontent.com/40423565/45195368-c595e980-b289-11e8-8edc-4ebf72ae3793.png)
![1536287678 1](https://user-images.githubusercontent.com/40423565/45195379-ccbcf780-b289-11e8-9ecb-62bd8118b176.png)
Is this? but this is still not good.

**Comment by Yorke81** [comment]
[Uploading TempCode.zip…]()
This is my project code.

**Comment by Yorke81** [comment]
[TempCode.zip](https://github.com/Zeus64/alcinoe/files/2359301/TempCode.zip)
This is my project code.

**Comment by Yorke81** [comment]
Can you compile and run the attachment project?

**Comment by Yorke81** [comment]
Can you compile and run the attachment project?

**Comment by Yorke81** [comment]
I read the previous documentation,this problem is solved. thanks

**Comment by Zeus64** [comment]
ok that's great :)
