### ISSUE TITLE
Orange Border

### ISSUE THREAD

**Issue by leonardoaa** [Zeus64/alcinoe#33]
HI, all AlEdit appears with a "orange border" when I select the component. How do I remove this?

I searched all properties but not remove this.

tks a lot,

Leo

![print](https://user-images.githubusercontent.com/14091683/48780341-d4a10b00-ecc0-11e8-861e-50cd0f80b59d.png)

**Comment by jhonalone** [comment]
Hi. Leo
Try this configuration and tell me if it solves the problem.
Remember two important things:
1, - Only useful from version 6 of Android. For previous versions you will have to incorporate in the Depoyment of your project the files of the folder "D: \ Dev \ Alcinoe \ demos \ ALFmxControls \ _source \ android \ res"
2.- You will have to adapt all the configuration paths of the file "AddRJavaToClassesDex.bat" and the rest of configuration files, such as the file "compilejar_tokyo.bat" and execute "compile_tokyo.bat" and etc. etc. you know what I mean.
I hope it helps you.
Best regards.
[OrangeBorder.zip](https://github.com/Zeus64/alcinoe/files/2617322/OrangeBorder.zip)
