### ISSUE TITLE
Support for Delphi Rio 10.3

### ISSUE THREAD

**Issue by CrustyLoaf** [Zeus64/alcinoe#34]
Hi - many thanks for your great work.
Any advice on how to install in the latest Delphi release?

**Comment by aloisjunior** [comment]
Many, many, many thanks for your great work!!!!!!!!!!!!!!!!!!!!!

**Comment by Zeus64** [comment]
I must first finish implementation of webrtc in delphi (peer to peer live video chat) and then i will work on the migration to Delphi Rio 10.3. It's will be ready in december I think

**Comment by marlonnardi** [comment]
Congratulations on the excellent work, looking forward to having it in 10.3

**Comment by Martifan** [comment]
+

**Comment by rzhghost** [comment]
many thanks for your great work!

**Comment by drcrck** [comment]
great components, thanks.
ideas for rio?

**Comment by rj1102** [comment]
I only use TAlText and TAlRectangle. Can I just use Alcinoe_tokyo with Delphi Rio or is that asking for trouble? Or will Rio version for Alcinoe been released soon? Or are rectangles and labels in Rio now fast enough in scrollboxes that alcinoe is obsolete in that area (wishfull thinking;))

**Comment by marlonnardi** [comment]
New? @Zeus64

**Comment by Martifan** [comment]
Please make for version Delphi Rio 10.3 
Thank you in advance

**Comment by CrustyLoaf** [comment]
Many thanks for the information @Zeus64 

I've searched Embarcadero blogs but can't find any news on Rio Update 1 at all.  Do you know about an expected release date for this?  Are we looking at weeks or months do you think?

**Comment by checkdigits** [comment]
@CrustyLoaf any news of when Rio Update 1 would be available is generally covered by an NDA so neither @Zeus64 or myself would be able to tell you even if we knew.  Embarcadero have previously released updates around this time of year to address various issues.  They don't usually have a fixed schedule for it as it tends to roll up as many fixes and stability issues as they possibly can which they didn't have time for in the primary release or have come to light subsequently.

What I can tell you is that there's a lot of activity going on at the moment 'behind the scenes' and my guess is that it will be a few weeks rather than several months.  If I was a gambling man - and I'm not - my money would be on some time in late February or early March but that is pure guesswork based on nothing more than gut feeling.

The official roadmap doesn't give any exact dates for the 2019 releases.  https://community.embarcadero.com/article/news/16638-rad-studio-august-2018-roadmap  😄

**Comment by CrustyLoaf** [comment]
Thanks @checkdigits your thoughts are much appreciated - hopefully all will become clear before too long :)

**Comment by tumaso** [comment]
@Zeus64
с марта 2019 года приложения, скомпилированные в 10.2.3 Tokyo, в AppStore не разместить

**Comment by moj127** [comment]
Great work! Thanks a lot.
How can I have your excellent component installed on 10.3.1? Is there a version for 10.3.1?

**Comment by checkdigits** [comment]
Unfortunately it’s not quite ready for 10.3.1 Rio at the moment. There are quite a few things that need to be done but it is planned. There’ll be an update when it’s available.

**Comment by Martifan** [comment]
UP!!!

**Comment by ycq323** [comment]
UP!!!

**Comment by rj1102** [comment]
What does "UP!!!" mean? Is it working now for Rio 10.3.1? I don't see any recent commits.

**Comment by tumaso** [comment]
We waiting...

**Comment by checkdigits** [comment]
Yeah I'm not sure what "up" is supposed to mean either - it perhaps means that the Delphi Rio 10.3.1 update is available which @Zeus64 was referring to in his comments when he said the Alcinoe port would be available after that.

**Comment by Martifan** [comment]
It means nothing, just a sign that we are waiting :) and not to forget about us

**Comment by tianshangyuan** [comment]
thanks

At 2019-04-09 06:45:22, "Martifan" <notifications@github.com> wrote:


It means nothing, just a sign that we are waiting :) and not to forget about us

**Comment by chuahyen** [comment]
It seems that the current version of alcinoe cannot be supported by Rio 10.3.1. I have problem even compiling the dpk. Any news?

**Comment by marlonnardi** [comment]
it is sad to see such a promising and high-quality project stopped.
I really admire your @Zeus64  code, I am inspired by many things in it, but it seems to me that even in the portal of the embarcadero you are inactive (https://quality.embarcadero.com/secure/ViewProfile.jspa?name=svanderclock) - "loki loki [X] (Inactive)" .

**Comment by tothpaul** [comment]
Hello guys, I see that some are complaining. I suppose even Zeus has to do some paid work to eat at the end of the month ... free solutions can wait and contributions are welcome.

**Comment by Zeus64** [comment]
@tothpaul you are 100% right :( Unfortunately, I needed to do some paid work in priority and this let me very few time for me... I thanks anyone for their contributions, I already installed Rio and I will work on it as soon as possible (I hope this month) ...

**Comment by marlonnardi** [comment]
what a great news @Zeus64 ! as can we help you with financial contributions?

**Comment by zomorango** [comment]
@Zeus64  you should have a donation system, like patreon or paypal donate :)

**Comment by Martifan** [comment]
@Zeus64 Specify your data where you can send money and who can send as much as possible. all work must be paid

**Comment by LIDERNetwork** [comment]
I agree with all of you! Send a payment link through Paypal and I will also make a contribution to the project, because your work is excellent and I admire it. Waiting for RIO version

**Comment by tumaso** [comment]
Hi.

Any news?

**Comment by proyectoanamnesis** [comment]
@Zeus64 Send a payment link through Paypal and I will also make a contribution to the project. Saludos desde Argentina

**Comment by viniciusfbb** [comment]
@Zeus64 Make a new branch named "Comunity" and one Slack channel to avoid us to contribute to this project. The project need to be rewritted, but since it's great, I don't have the time to do it all, just like you, but I can help with some of it

**Comment by Zeus64** [comment]
@viniciusfbb I don't know if we really need a branch as you can put here some push request :)
anyway I have already migrated everything to Rio, our main app is already working with alcinoe on Rio, I just need a little more time to "recheck" everything before to commit (i don't like to commit when not very well tested)

**Comment by viniciusfbb** [comment]
Very good! 👏🏻👏🏻

**Comment by azzahrah** [comment]
Amazin....

**Comment by andrecampestre** [comment]
Very good, I hope this version comes out soon. Good luck!

**Comment by PonyPC** [comment]
you are the star in dark space

**Comment by andrecampestre** [comment]
@Zeus64 
Hey yo! Do you have some news about Support for Delphi Rio?

Thanks

**Comment by Zeus64** [comment]
I m working on it, everything is already done I m just testing everything right now

**Comment by dluisbrbr** [comment]
Do you have some news about Support for Delphi Rio?

**Comment by dluisbrbr** [comment]
what are the procedures for installing the components in Rad Studio Rio Arch?

**Comment by Zeus64** [comment]
Thanks everyone for your patience and sorry for the delay :( 
I just committed the version compatible with Rio 10.3.1

**Comment by marlonnardi** [comment]
Thank you so much for this!

**Comment by rzhghost** [comment]
Thank you very much！




| |
荣植华
邮箱：rzhcrystal@163.com
|

签名由 网易邮箱大师 定制

On 06/23/2019 07:47, Marlon Nardi wrote:

Thank you so much for this!

**Comment by proyectoanamnesis** [comment]
Excelente trabajo. Eres el mejor!

**Comment by Spelt** [comment]
Thanks!! Much appreciated!

**Comment by CrustyLoaf** [comment]
Many thanks!

I must be doing something wrong though as I am getting a compiler error in ALFmxLayouts.pas:

[dcc32 Error] ALFmxLayouts.pas(142): E2137 Method 'ChildrenMouseDown' not found in base class
[dcc32 Error] ALFmxLayouts.pas(143): E2137 Method 'ChildrenMouseMove' not found in base class
[dcc32 Error] ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseUp' not found in base class
[dcc32 Error] ALFmxLayouts.pas(145): E2137 Method 'ChildrenMouseLeave' not found in base class
[dcc32 Fatal Error] Unit1.pas(12): F2063 Could not compile used unit 'ALFmxLayouts.pas'

I tried uncommenting the $ALDPK define in Alcinoe_rio.dpk and rebuilding and installing the BPL but it doesn't make any difference.

Has anybody else seen this problem and fixed it?

**Comment by andrecampestre** [comment]
@CrustyLoaf I have The same problem.

**Comment by Zeus64** [comment]
hi, that because you need to include in your search path 

\Alcinoe\references\embarcadero\rio\10_3_1\patched\fmx\

If it's still fail to compile then you will also need to include in your search path some files taken from your delphi\src\ directory

**Comment by CrustyLoaf** [comment]
Thanks @Zeus64 

I have the following remaining error now:

[dcc32 Fatal Error] FMX.Types3D.pas(1023): F2051 Unit FMX.Materials was compiled with a different version of FMX.Types3D.TMaterial

Any thoughts on that one?

**Comment by Zeus64** [comment]
yes, it what I said previously, you need now to take this file from you delphi source directory (C:\Program Files (x86)\Embarcadero\Studio\20.0\source\) and copy it somewhere in the search path of your project.

in alcinoe i copy those file in C:\Dev\Alcinoe\references\embarcadero\rio\10_3_1\originals\

**Comment by gbarroslimajr** [comment]
'm having trouble with FMX.Filter.pas, the unit is already in the path "alcinoe-master \ references \ pier \ river \ 10_3_1 \ patched \ fmx"

**Comment by RODRIGOCOLLARES** [comment]
> @CrustyLoaf I have The same problem.
Hello, how are you? I checked that I'm having the same error here in my delphi 10.3.2. The component works fine after adding the correct directories in the library path, but when I use other components it always gives me error of "such a unit was compiled by another version". Could you tell me what I do to get this resolved? Thank you very much

**Comment by RODRIGOCOLLARES** [comment]
> Many thanks!
> 
> I must be doing something wrong though as I am getting a compiler error in ALFmxLayouts.pas:
> 
> [dcc32 Error] ALFmxLayouts.pas(142): E2137 Method 'ChildrenMouseDown' not found in base class
> [dcc32 Error] ALFmxLayouts.pas(143): E2137 Method 'ChildrenMouseMove' not found in base class
> [dcc32 Error] ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseUp' not found in base class
> [dcc32 Error] ALFmxLayouts.pas(145): E2137 Method 'ChildrenMouseLeave' not found in base class
> [dcc32 Fatal Error] Unit1.pas(12): F2063 Could not compile used unit 'ALFmxLayouts.pas'
> 
> I tried uncommenting the $ALDPK define in Alcinoe_rio.dpk and rebuilding and installing the BPL but it doesn't make any difference.
> 
> Has anybody else seen this problem and fixed it?

Hello, how are you? I checked that I'm having the same error here in my delphi 10.3.2. The component works fine after adding the correct directories in the library path, but when I use other components it always gives me error of "such a unit was compiled by another version". Could you tell me what I do to get this resolved? Thank you very much

**Comment by CrustyLoaf** [comment]
@RODRIGOCOLLARES I have things working with Rio 10.3.1 but I haven't updated to 10.3.2 yet.

Here are the notes I made for myself to remember how to install in future:

Firstly add the following folders to the Library Path:
**\Alcinoe\trunk\source
\Alcinoe\trunk\references\embarcadero\rio\10_3_1\patched\fmx**

Note: Depending on the target platform, you may also need to add some of the following folders:
**\Alcinoe\trunk\references\embarcadero\rio\10_3_1\patched\rtl\android
\Alcinoe\trunk\references\embarcadero\rio\10_3_1\patched\rtl\ios
\Alcinoe\trunk\references\embarcadero\rio\10_3_1\patched\rtl\net**

Install the component package by opening, building and installing this:
**\Alcinoe\trunk\source\Alcinoe_rio.dproj**

Note:  In your own project you may experience further compile errors such as this:
 
![Compile Error](https://user-images.githubusercontent.com/16792031/61706752-ca984600-ad40-11e9-9b76-52bedb5f3b3d.jpg)

In such cases, copy the specified original source file to a new folder created here:
**\Alcinoe\trunk\references\embarcadero\rio\10_3_1\originals**

Add this folder to the Library Path too.

Note that the Embarcadero source files can all be found within the Source folder here:
**C:\Program Files (x86)\Embarcadero\Studio\20.0\source\**
 
![File Copy](https://user-images.githubusercontent.com/16792031/61707225-de907780-ad41-11e9-8e79-87325a46ccf8.jpg)

**Comment by RODRIGOCOLLARES** [comment]
Thank you very much... i tried here with other way and now it works perfctly... ive made a test pushing  at least 50 different kind of visual components and there were no issues never more... i can say now alcinoe works at delphi rio update2, but you have to delete 3 child's methods on 2 units (alfmxlayouts and alfmxcontrols). After this you have to add on library path only the originals path in first off all the list. The patched files only at the end of the library path list.

**Comment by megatkurniawan** [comment]
> 
> 
> Thank you very much... i tried here with other way and now it works perfctly... ive made a test pushing at least 50 different kind of visual components and there were no issues never more... i can say now alcinoe works at delphi rio update2, but you have to delete 3 child's methods on 2 units (alfmxlayouts and alfmxcontrols). After this you have to add on library path only the originals path in first off all the list. The patched files only at the end of the library path list.

i have same problem with tokyo, i try following this but if compile in android just stuck splash screen.

**Comment by artdelphi** [comment]
@Zeus64
have the following remaining error now:

[dcc32 Fatal Error] FMX.Forms.pas(1385): F2051 Unit FMX.ZOrder was compiled with a different version of FMX.Forms.TCommonCustomForm

Any thoughts on that one?

build in delphi 10.3.3
