### ISSUE TITLE
The splash image does not appear.

### ISSUE THREAD

**Issue by jhonalone** [Zeus64/alcinoe#35]
And now, can someone tell me how I have to configure the Deployment, so that the application shows the splash image when it starts?
Many thanks in advance.
Best regards.

**Comment by Zeus64** [comment]
hi jhonalone, did you finally find a way out for the splash image ?

**Comment by jhonalone** [comment]
No. Unfortunately I did not get it. The main use I wanted to make of the Alcinoe component library was to solve the Delphi problem with TMemo and TEdit. It seems that I did not get it with the Tokyo version or with the Seattle version. So I have resigned.
I'm going to close the thread.
Best regards.
