### ISSUE TITLE
TALVideoPlayerSurface how to upload a new video? 

### ISSUE THREAD

**Issue by Martifan** [Zeus64/alcinoe#36]
Hello
how to upload a new video? 
how not tried everything is not successful
thx.

**Comment by Yarpda** [comment]
It is nice tool, but can it plays local files. Iam tryed to give it fiepath, but nothing happend. Please answer, may by i dooing something wrong...

**Comment by Zeus64** [comment]
yes i guess it's possible, ALVideoPlayer uses https://exoplayer.dev/ so better to look on exoplayer how to do ...

**Comment by Martifan** [comment]
You can play videos from youtube?
if you specify the address of the video?

**Comment by Zeus64** [comment]
@Martifan I really doubt youtube will let other play like this their video ... so i guess no

**Comment by Martifan** [comment]
Thank you

**Comment by Spelt** [comment]
Maybe you can download it and then play it. 

There are tools/libs for downloading vids from youtube.
