### ISSUE TITLE
TAlVideoPlayerSurFace: How to interrupt video loading (android)

### ISSUE THREAD

**Issue by VanarGames** [Zeus64/alcinoe#364]
Good day!
Tell me how to interrupt video file loading in TAlVideoPlayerSurFace

My scenario is as follows:

1. From the main form I call the FmVideo form:

Application.CreateForm(TFmVideo, FmVideo);
...
Player.VideoPlayer.OnError := VideoPlayerOnError;
Player.VideoPlayer.prepare('http://...mp4', True)
...
FmVideo.Show();

I see that Player.VideoPlayer.state In [vpsPrepared]

2. I immediately close the FmVideo form, without waiting for the video to load.
3. I open FmVideo again and immediately close it.
4. After three actions of point 3, the application records the fact of the error in VideoPlayerOnError
and issues: Player.VideoPlayer.state In [vpsIdle]

How to completely interrupt downloads when closing the FmVideo form, restore the state of Player.VideoPlayer?

I tried Player.resetVideoPlayer when closing the FmVideo form - it does not help!

**Comment by Zeus64** [comment]
To interrupt the downloads when closing FmVideo you must do 

VideoPlayer.AutoStartWhenPrepared := False;
VideoPlayer.stop;

**Comment by VanarGames** [comment]
Thanks a lot
