### ISSUE TITLE
ALLiveVideoChat Client

### ISSUE THREAD

**Issue by Martifan** [Zeus64/alcinoe#40]
Hello All
help please solve the problem, I can not compile the client gives an error message:

[Exec Error] The command "PATH C:\Program Files (x86)\Java\jdk1.8.0_131\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBaseXE7\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\17.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\17.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\InstallAware X6;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Java\jdk1.8.0_131\bin & "C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.0\dx.bat" --dex --output="C:\Alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "C:\Alcinoe\lib\jar\org.webrtc\webrtc.jar"" exited with code 2.

**what is the problem?**
**Thank you in advance**

**Comment by Zeus64** [comment]
can you run the command in cmd.exe ?
this one: 

`"C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.0\dx.bat" --dex --output="C:\Alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "C:\Alcinoe\lib\jar\org.webrtc\webrtc.jar"`

**Comment by Martifan** [comment]
UNEXPECTED TOP-LEVEL EXCEPTION:
java.io.FileNotFoundException: C:\Alcinoe\lib\jar\org.webrtc\webrtc.jar (╤шёЄхьх эх єфрхЄё  эрщЄш єърчрээ√щ яєЄ№)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:165)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:143)
        at com.android.dx.command.dexer.Main.processOne(Main.java:678)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:575)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
        at com.android.dx.command.dexer.Main.runDx(Main.java:288)
        at com.android.dx.command.dexer.Main.main(Main.java:244)
        at com.android.dx.command.Main.main(Main.java:95)
1 error; aborting

**Comment by Zeus64** [comment]
it's because you need to use \Alcinoe\tools\D8Proxy\dx.bat instead of the dx.bat in you SDKPath. this because delphi do not support yet d8.bat

**Comment by Martifan** [comment]
Hello
I did as you said, but I get an error:

[Exec Error] The command "PATH C:\Program Files (x86)\Java\jdk1.8.0_131\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\17.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\17.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\InstallAware X6;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Java\jdk1.8.0_131\bin & "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" --dex --output="D:\Delphi\Isxodniki\Android\Gocha\NewVersion\Client\Enigma\Components\Alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\Delphi\Isxodniki\Android\Gocha\NewVersion\Client\Enigma\Components\Alcinoe\lib\jar\org.webrtc\webrtc.jar"" exited with code 1.

**Comment by Martifan** [comment]
when i write cmd:
`"C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" --dex --output="D:\Delphi\Isxodniki\Android\Gocha\NewVersion\Client\Enigma\Components\Alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\Delphi\Isxodniki\Android\Gocha\NewVersion\Client\Enigma\Components\Alcinoe\lib\jar\org.webrtc\webrtc.jar"`
Return:
`Error in C:\SDKs\android-sdk-windows\platforms\android-28\android.jar:
  Error with library file: C:\SDKs\android-sdk-windows\platforms\android-28\android.jar
Compilation failed
Deleted file - C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.~tmp
`

**Comment by Mbear07** [comment]
Hi there, I had the same problem, I am using Rio 10.3.3 and for me the solution was : 

1. step : replace the "C:\SDK..". in the "new" dx,bat with the actual path 
(eg C:\Users\Public\Documents\Embarcadero\Studio\20.0\CatalogRepository\AndroidSDK-2525_20.0.36039.7899\platforms\android-28\)

2. step: I needed to create "C:\DEV\Alcinoe" directory and copy the "lib" directory to the this path
(because this was the problem when with the file:  alcinoe-webrtc.jar )

**Comment by Martifan** [comment]
Thanks for the answer.
Please tell me where to get the latest version **dx,bat**?

**Comment by Mbear07** [comment]
I've just used the latest from the github...
alcinoe/tools/D8Proxy/
Sorry for my English; I wanted to say that I replaced the "original" sdk dx.bat with the "new" alcione dx.bat and did the changes. 
BUT... although I could build it it's crashing on the android device. I created an issue but no answer yet.

**Comment by Martifan** [comment]
Thank you very much I understood everything
