### ISSUE TITLE
User-Agent for AVPlayer

### ISSUE THREAD

**Issue by enri690** [Zeus64/alcinoe#48]
How do you set an User-Agent for AVPlayer?
I already did it for Exoplayer.

**Comment by enri690** [comment]
Thanks. Found it.

**Comment by yassinov12** [comment]
Hi
Please what's the method to add the "User-Agent" header attached to play request with ALVideoPlayerSurface?

**Comment by Zeus64** [comment]
Hello, exoplayer use a "default" user agent. If you need to expose this property then you will need to update a little the source code
