### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by landrix** [Zeus64/alcinoe#5]
hi, is this git repo the official project replacement for http://alcinoe.svn.sourceforge.net/viewvc/alcinoe/ ?
or just a copy?

**Comment by Zeus64** [comment]
Both are synchronized so you can choose with you prefer ! github offer Git for people who like git and sourceforge offer svn for people who prefer svn. Personally i prefer SVN But sourceforge  suck on support / issue tracking and have a very ugly design for presenting the project.

just one remark, git don't support file over 200 mb, so big sample json/xml file included in demo are available only on svn
