### ISSUE TITLE
Apply TBitmap to TALImage

### ISSUE THREAD

**Issue by tumaso** [Zeus64/alcinoe#51]
Hi.

How to apply TBitmap (from memory) to TALImage without using FileName or ResourceName?

Thanks!

**Comment by tumaso** [comment]
No comments/support from @Zeus64. Sorry, but it's very very wrong. 
This library not for real projects.

**Comment by Zeus64** [comment]
actually TALImage is made to handle only image from resourceName/UIDatePicker. it's quite the same as Timage for other behavior so if you need to handle TBitmap no need to use TALImage you can directly use Timage
