### ISSUE TITLE
Custom font for TAlText

### ISSUE THREAD

**Issue by tumaso** [Zeus64/alcinoe#52]
Hi.

How to use custom font with TALText on Android/iOS? My app deploys custom fonts, TLabel and TEdit (standart FMX controls) use it successfully, but TALText ignores any custom font...

**Comment by Zeus64** [comment]
TALText use the android api Paint (ie: JPaint in Delphi) to draw itself. It set the font via Paint.setTypeface(...). 

this is the code:

{code}
            JStr1 := StringToJString(aOptions.FontName); // << https://quality.embarcadero.com/browse/RSP-14187
            aTypeface := TJTypeface.JavaClass.create(JStr1, aStyle);
            aPaint.setTypeface(aTypeface);
            aTypeface := nil;
            JStr1 := nil;
{code}

So you must make your font available to the android API ... check the deployment of your font

**Comment by bravesoftdz** [comment]
not enough answer
