### ISSUE TITLE
TALText: html tags do not have to be exact

### ISSUE THREAD

**Issue by rj1102** [Zeus64/alcinoe#55]
Just a minor code documentation issue while testing Rio: 

ALFmxCommon.pas says in line 328, 345, 356, 366, 3241, 4107, 4139, 4171:  "support only theses EXACT html tag"
However it appears that tag names do not have to be exact, e.g. <b> can also been replaced by <bold> or <better_be_bold> or any other tag starting with a "b".

**Comment by rj1102** [comment]
Just a minor code documentation issue while testing Rio:

ALFmxCommon.pas says in line 328, 345, 356, 366, 3241, 4107, 4139, 4171: "support only theses EXACT html tag"
However it appears that tag names do not have to be exact, e.g. &lt;b> can also been replaced by &lt;bold> or &lt;better_be_bold> or any other tag starting with a "b".

**Comment by Zeus64** [comment]
@rj1102 it's a bug in the implementation, actually the process is little rough and not made to receive input directly from client (where we must carefully check the tag) !

**Comment by Zeus64** [comment]
It's now corrected in the last commit, thanks for the problem report!
