### ISSUE TITLE
How do I use <img> and <span> in TALText?

### ISSUE THREAD

**Issue by rj1102** [Zeus64/alcinoe#56]
Comments in ALFmxCommon say that TALText also supports &lt;img src="xxx"> and &lt;span id="xxx">...&lt;/span>
But how do I use these?
I tried AlText1.Text := '&lt;img src="C:\Test.jpg">, but I get EResNotFound exception at runtime.

**Comment by Zeus64** [comment]
you must write the name of an image resource (ex: "Test") of an image you add in the project and not a filepath

**Comment by rj1102** [comment]
So I added a file (Test.png) to my Android deployment configuration, remote path ".\" and remote name "Test.png".
How should i address to it in the img tag?
