### ISSUE TITLE
Is it compatible with Delphi Rio 10.3 ?

### ISSUE THREAD

**Issue by Maher7Tannous** [Zeus64/alcinoe#57]
I have compiled it with delphi rio 10.3 but I have some errors
I can't compile android application using TALText or TALMemo
unit ALFmxCommon;
[DCC Error] ALFmxCommon.pas(5951): E2003 Undeclared identifier: 'ConvertPixelToPoint'

**Comment by Zeus64** [comment]
You need to include in your search path the delphi patched file located in \Alcinoe\references\embarcadero\rio\10_3_1\patched. I guess you still have in your path the delphi tokyo source file
