### ISSUE TITLE
TALFMXLayouts Error

### ISSUE THREAD

**Issue by azzahrah** [Zeus64/alcinoe#58]
Howto solve problem like below:

[DCC Error] ALFmxLayouts.pas(142): E2137 Method 'ChildrenMouseDown' not found in base class
[DCC Error] ALFmxLayouts.pas(143): E2137 Method 'ChildrenMouseMove' not found in base class
[DCC Error] ALFmxLayouts.pas(144): E2137 Method 'ChildrenMouseUp' not found in base class
[DCC Error] ALFmxLayouts.pas(145): E2137 Method 'ChildrenMouseLeave' not found in base class
[DCC Fatal Error] main.pas(19): F2063 Could not compile used unit 'ALFmxLayouts.pas'

**Comment by mikelustosa** [comment]
Você deve comentar todos esses métodos.

**Comment by azzahrah** [comment]
@mikelustosa Okay, I did it
