### ISSUE TITLE
Firemonkey video player How to play video from local disk?

### ISSUE THREAD

**Issue by D4n16l6** [Zeus64/alcinoe#60]
Sorry but I don't understand to play video on TALVideoPlayerSurface with project Win32/64. I must use another component? A small sample code?

**Comment by MuminjonGuru** [comment]
Here is a sample application which can give an idea about how to play video from local disk, but now the TALVideoPlayerSurface component. This sample demonstrates the use of the TMediaPlayer and the TMediaPlayerControl components.  http://docwiki.embarcadero.com/CodeExamples/Rio/en/FMX.Mobile.VideoPlayback_Sample

**Comment by bagualing** [comment]
I took a look at the source code in alcinoe. Alcinoe currently does not support playing multimedia files in Windows. The TALWinVideoPlayer class is empty ( is not implemented).
Maybe you can submit a functional requirement.

**Comment by Zeus64** [comment]
@bagualing yes TalVideoPlayer is currently not implemented under windows. it's made only for ios / android.
