### ISSUE TITLE
fmx.effects not found

### ISSUE THREAD

**Issue by gbarroslimajr** [Zeus64/alcinoe#61]
I added the paths as informed, added the following:
* alcinoe-master \ source
* alcinoe-master\references\embarcadero\rio\10_3_1\originals
* alcinoe-master\references\embarcadero\rio\10_3_1\ patched \ fmx

But when I inform the 3 path, it returns the error:

fmx.effects not found

**Comment by gbarroslimajr** [comment]
alcinoe-master\references\embarcadero\rio\10_3_1\originals

**Comment by gbarroslimajr** [comment]
solved.

**Comment by pasiek22** [comment]
I have the same problem. How did you solve this problem?
