### ISSUE TITLE
Unable to Install ALFmxControls Demo to IOS

### ISSUE THREAD

**Issue by MayoZelaya** [Zeus64/alcinoe#69]
The Demo compile ok for IOS but when installing to device I get the Error 
"Unable to install package.(e800004c). I'm using Delphi 10.3.1 and IOS 12.3.1.
I can deploy other apps with no problem.

Any help?

Thanks in Advance,

Omar Zelaya

**Comment by Zeus64** [comment]
It's often a big mystery to understand the exact cause of such message (like e800004c). there is no help about it and it's a black box :( make sure you compile the 64 bit but except this, I do not have too much idea sorry
