### ISSUE TITLE
Android and IOS64 compile components problem

### ISSUE THREAD

**Issue by pasiek22** [Zeus64/alcinoe#72]
Hello,

I have Delphi 10.3.1.
I have installed components for WIN32.  (I used source\Alcinoe_rio.dproj file)
However, when I try to compile for Android and IOS64 I get an error:

[DCC Error] Alcinoe_rio.dpk(36): E2029 'END' expected but identifier 'DesignIDE' found

What should I do ?
Thank you for your help.

**Comment by pasiek22** [comment]
Hi !!

Any ideas ?

**Comment by Zeus64** [comment]
Hi, not really :( I don't have this error ... hard to help you if I can not reproduce :(

**Comment by Zeus64** [comment]
Ok i found, for ios and android you don't need the Alcinoe_rio.dpk ! it's only a design package (use by the IDE to show visual component on the form) and can be compiled ONLY on win32 ...

**Comment by Zeus64** [comment]
you can use compile_rio.bat to compile the package and after install it in the ide (or use the already compiled one located in Alcinoe\lib\bpl\alcinoe\Win32\rio)

**Comment by pasiek22** [comment]
Thank you !!! I will try.
And one more question. Are the components compatible for version 10.3.2?

**Comment by Zeus64** [comment]
I didn't yet upgrade to 10.3.2 :(

**Comment by Zeus64** [comment]
this must be updaded to 10.3.2:  \Alcinoe\references\embarcadero\rio
that all
