### ISSUE TITLE
Firebase Cloud Messaging

### ISSUE THREAD

**Issue by houlding** [Zeus64/alcinoe#77]
I have an issue on ALFirebaseMessagingDemo running on iOS 12.4. The token is generated but when I send a message to the app, it's not received. 

I do get a success message from the POST: 

{"multicast_id":6062576438669598918,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1567564727335713%c10238ecc10238ec"}]}

but the OnMessageReceived event never fires. Any ideas?

**Comment by houlding** [comment]
My bad. You need to connect to the client to receive messages. Can I suggest you add that part to the demo? Hopefully it'll save someone the same frustrations.

**Comment by zomorango** [comment]
> You need to connect to the client to receive messages

Hi Houlding,  I'm testing the firebase messaging on ios, I get the same problem as you, but what do you mean by "You need to connect to the client to receive messages"?

Can you help me?
