### ISSUE TITLE
IOS64 compile problem 

### ISSUE THREAD

**Issue by pasiek22** [Zeus64/alcinoe#78]
Hi !
I have a very urgent issue. Everything is OK for android. But as I try to recompile the project for IOS64 I get the following error. Can anyone tell me how to solve it?

[DCC Error] ALGraphics.pas(3335): E2003 Undeclared identifier: 'setValueforKey'
[DCC Error] ALGraphics.pas(3335): E2003 Undeclared identifier: 'kCIInputImageKey'
[DCC Error] ALGraphics.pas(3338): E2003 Undeclared identifier: 'setValueforKey'
[DCC Error] ALGraphics.pas(3339): E2003 Undeclared identifier: 'setValueforKey'
[DCC Error] ALGraphics.pas(3339): E2003 Undeclared identifier: 'kCIInputRadiusKey'
[DCC Error] ALGraphics.pas(3525): E2003 Undeclared identifier: 'setValueforKey'
[DCC Error] ALGraphics.pas(3525): E2003 Undeclared identifier: 'kCIInputImageKey'
[DCC Error] ALGraphics.pas(3528): E2003 Undeclared identifier: 'setValueforKey'
[DCC Error] ALGraphics.pas(3529): E2003 Undeclared identifier: 'setValueforKey'
[DCC Error] ALGraphics.pas(3529): E2003 Undeclared identifier: 'kCIInputRadiusKey'
[DCC Fatal Error] F2063 Could not compile used unit 'ALGraphics.pas'

**Comment by pieomy** [comment]
Hi,

Use google
search this keywords 'kCIInputImageKey', 'iOS', 'SDK', 'Link'

same issues;
https://github.com/Zeus64/alcinoe/issues/16
https://github.com/Zeus64/alcinoe/issues/24
