### ISSUE TITLE
RIO 10.3.2?

### ISSUE THREAD

**Issue by alissonrodrigo** [Zeus64/alcinoe#85]
not compatible with Delphi RIO 10.3.2?

**Comment by tumaso** [comment]
Forgot about 10.3.2. Now is 10.3.3 time.

**Comment by pasiek22** [comment]
@tumaso but components are not compatible with Delphi RIO 10.3.3 :)

**Comment by viniciusfbb** [comment]
While Stephane does not release the official version, I made a pull request with Delphi Rio 10.3.2 and 10.3.3 compatibility.

In the case of 10.3.2, it has been 100% tested and works perfectly, but in 10.3.3, although it is working, I haven't tested everything yet.

https://github.com/Zeus64/alcinoe/pull/74

**Comment by Zeus64** [comment]
Hello, we are now moved to 10.4.2 so I close this Issue
