### ISSUE TITLE
Tabcontrol crash

### ISSUE THREAD

**Issue by Spelt** [Zeus64/alcinoe#86]
Hi

Thanks for the lib. Really nice.

I noticed a crash when:

1. Programmatically add a few tabs
2. Slide a tab
3. Free all tabs
4. Programmatically add tabs.

This is because when sliding the FAniTransition.Parent is set to the active tab.  When this tab is freed, so is FAniTransition.

**Solution:**

```
destructor TALTabItem.Destroy;
begin

  if (TabControl.FAniTransition <> nil) and (TabControl.FAniTransition.Parent = self) then
  begin
    TabControl.FAniTransition.Parent := nil;
  end;

  inherited;
end;

```

Sincerely, Edward

**Comment by Spelt** [comment]
sorry for the many edits.

**Comment by Zeus64** [comment]
corrected in the last commit! thanks for the correction !!
