### ISSUE TITLE
Error 0xe800004c building iOS Version ALFMXControls

### ISSUE THREAD

**Issue by SDiestelmann** [Zeus64/alcinoe#9]
Hi I tried to build the new ALFMXControls Demo with latest 10.2.3 and iOS 11.3 Patch.
The iOS installer throws error e800004c - and i can not find a description of this error, nor find a reason for it.

Any idea ?

**Comment by Zeus64** [comment]
Ok, i found it out (finally). delphi 10.2.3 is not compatible with iOS 11.3. you must try with iOS 11.2 or wait for the next release of delphi. Exemple of bug with iOS 11.3: https://quality.embarcadero.com/browse/RSP-20728?jql=text%20~%20%22ios%2011.3%22

please don't forget to like (star) this project under github
