### ISSUE TITLE
Use alcinoe with other components

### ISSUE THREAD

**Issue by panmilkos** [Zeus64/alcinoe#90]
First of all thanks for the great job.
Second ... i want to include alcinoe in a project with other components pack but i have just the dcu's.
I copy the dcu's and all the other files to 'original' directory (I have it to search path), but nothing.
What can i do with this problem?
Thanks.

**Comment by Zeus64** [comment]
What do you mean by "other components pack" ? in original it's to copy inside the original delphi source code found in C:\Program Files (x86)\Embarcadero\Studio\20.0\source

**Comment by panmilkos** [comment]
With other components with source code all works fine.
I want to work with with some components from orangeui, but they give only the dcu (no .pas).
Without alcinoe works fine , but with it i have the error 
F2051 Unit uGraphicCommon was compiled with a different version of FMX.Objects.TRectangle

**Comment by Zeus64** [comment]
ah yes, understand, so no way to use the other components with Alcinoe if you don't have the source code of those components, This because I patched the original firemonkey delphi source code :(
