### ISSUE TITLE
YUV420P texture

### ISSUE THREAD

**Issue by TetrisSQC** [Zeus64/alcinoe#92]
Hi,

I'd like to get my video player running with your texture handling. Do you have a suggestion how to draw Y U V data to your texture class?

Christian

**Comment by Zeus64** [comment]
Hi tetris, is you video player under ios/android or under Windows ?

**Comment by TetrisSQC** [comment]
The code should run on all platforms. I attached the complete project which is an updated version of https://github.com/TetrisSQC/StreamPlayer. 

[ffmpeg.zip](https://github.com/Zeus64/alcinoe/files/4179759/ffmpeg.zip)

Christian

**Comment by Zeus64** [comment]
actually YUV420P work only on android / ios, i use OS api for that. I have no idea how to do this under windows
