### ISSUE TITLE
virus detected

### ISSUE THREAD

**Issue by megatkurniawan** [Zeus64/alcinoe#93]
I made an Android application when it was installed on a device with the brand xia**mi with the factory default antivirus reads like this picture. has anyone experienced the same thing? and with the same look I use the default component fmx antivirus not reading trojans?

![photo_2020-02-13_10-12-57](https://user-images.githubusercontent.com/25611625/74398576-b043c800-4e4a-11ea-9f0e-8031e7182cc2.jpg)

**Comment by Zeus64** [comment]
Yes I heard about this on Windows too. Just compiling a blank win32 app under Delphi Rio results in virustotal of many false detections. I was not aware that it's was also the case under Android :(
