### ISSUE TITLE
ALVideoPlayer in IOS 

### ISSUE THREAD

**Issue by caksongur** [Zeus64/alcinoe#94]
Hello,
Your work is excellent. I have a question. In ALVideoPlay, FPlayer.addObserver gives "undeclared identifier" error when compiling for IOS . Where did I go wrong?

**Comment by Zeus64** [comment]
hmm with version of iOS ? Did you also include the "patched" delphi source code located in /reference/embarcadero/ ?

**Comment by caksongur** [comment]
Yes. I use "patched" delphi source code. 
FMX.Canvas.GPU.Helpers.pas
FMX.Canvas.GPU.pas
FMX.Context.GLES.pas
FMX.Filter.pas
FMX.Forms.pas
FMX.Graphics.pas
FMX.Materials.Canvas.pas
FMX.Platform.Android.pas
FMX.Platform.iOS.pas
FMX.Platform.pas
FMX.Platform.UI.Android.pas
FMX.Types3D.pas

**Comment by Zeus64** [comment]
and the rtl directory ? \references\embarcadero\rio\10_3_3\patched\rtl\

**Comment by caksongur** [comment]
Yes. 
I forgot rtl directory. But This time it gives the following error. Our version 10.3.3.
"[DCC Fatal Error] iOSapi.Foundation.pas(6573): F2051 Unit System.IOUtils was compiled with a different version of iOSapi.Foundation.NSFileManager"

**Comment by Zeus64** [comment]
yes it's because you need ALSO to include in your path the original Delphi source code located in C:\Program Files (x86)\Embarcadero\Studio\20.0\source
