### ISSUE TITLE
TAlEdit crash in Android with Delphi 10.3.3

### ISSUE THREAD

**Issue by proyectoanamnesis** [Zeus64/alcinoe#96]
Hello guys.

Into form put a TAlEdit controls. Then I try run into my Android device, but I see the next message:

First chance exception at $C9D917B1. Exception class EJNIException with message 'java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader java.lang.Class.getClassLoader()' on a null object reference'. Process Project1.apk (2061)

I use:
Delphi 10.3.3 Version 26.0.36039.7899 
Android Device: Android 7.0

**Comment by Zeus64** [comment]
hello, can you try to install this app on your android device: https://tinyurl.com/zoxavr9
and say me if it's also crash ?

**Comment by proyectoanamnesis** [comment]
thanks for comment.
The App that you send me work ok. But I recorded a video and I share it, so you can see the error.

I create on empty project and put into form two AlEdit then I press F9 to run into my device. Please see the video to more details

[http://www.mediafire.com/file/0at1o4bac0nng91/WhatsApp_Video_2020-02-21_at_18.30.44.mp4/file](url)

**Comment by proyectoanamnesis** [comment]
After researching your example code, I saw that you had two units, then add this two units to my project

- Alcinoe-Common.jar 
- alcinoe-editText.jar

Then my app run ok into my Device.

**Comment by Zeus64** [comment]
@proyectoanamnesis yes of course the .jar was necessaries :) happy that everything work on your side, so I close this ticket
