### ISSUE TITLE
Delphi 10.2.3 does not work gives an error

### ISSUE THREAD

**Issue by Igor-kz** [Zeus64/alcinoe#97]
I'm trying to create a simple project on 10.2.3 but when compiling I get an error "[DCC Fatal Error] ALFmxCommon.pas(654): F2613 Unit 'FMX.Platform.UI.Android' not found."
Everything works on version 10.3.1, but how to make it work on Tokyo?
Thanks!

**Comment by Zeus64** [comment]
unfortunatly Alcinoe work only with the last version of Delphi (Rio 10.3.3). :( Unfortunatly I have no time to make all new development retro-compatible (with 10.2.3 for example). But anyway you can look for patch rio unit in Alcinoe\references\embarcadero\tokyo\10_2_3\patched but you will need to correct the Alcinoe code by yourself. Anyway be aware that with tokyo you can not deploy your app to the play store as the play store require 64 bit support and this is only in delphi 10.3.3
