### ISSUE TITLE
C++ Builder??

### ISSUE THREAD

**Issue by Aggie85** [Zeus64/alcinoe#98]
Howdy!

I am finally starting to setup a development environment with Rad Studio 10.3.3 to target  Android / IOS.

Alcinoe components hit a lot of NEEDS!

Has anyone used them with C++ Builder?

Thanks in advance,

Aggie85

**Comment by Zeus64** [comment]
hello @Aggie85, personally I never test it under c++ builder, but feel free to try it, and if need a little patch to work, just come back here :)
