### ISSUE TITLE
ImageMagick Access Violation

### ISSUE THREAD

**Issue by baronbanjo** [Zeus64/alcinoe#99]
AccessViolation error :
First chance exception at $005FD2F3. Exception class $C0000005 with message 'access violation at 0x005fd2f3: read of address 0x00000010'. Process ImageMagickTest.exe (3492)

happen when executing samples from readme.md at line ::

 aWand := ALImageMagickLib.NewMagickWand;

Any advice whats needed to run this ?

**Comment by viniciusfbb** [comment]
your program is not finding the ImageMagick dlls. You can copy the files of the ImageMagick to the path of your program. You can find all files in "alcinoe\lib\dll\imagemagick"

**Comment by Zeus64** [comment]
thanks @viniciusfbb ! I have updated the homepage readme.md with this info.
